// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Area.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CityInfo;
@class CountyInfo;
@class ProvinceInfo;
@class TownInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AreaRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface AreaRoot : GPBRootObject
@end

#pragma mark - AreaInfo

typedef GPB_ENUM(AreaInfo_FieldNumber) {
  AreaInfo_FieldNumber_ProvinceListArray = 1,
};

@interface AreaInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ProvinceInfo*> *provinceListArray;
/// The number of items in @c provinceListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger provinceListArray_Count;

@end

#pragma mark - ProvinceInfo

typedef GPB_ENUM(ProvinceInfo_FieldNumber) {
  ProvinceInfo_FieldNumber_ProvinceId = 1,
  ProvinceInfo_FieldNumber_ProvinceName = 2,
  ProvinceInfo_FieldNumber_CityListArray = 3,
};

@interface ProvinceInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t provinceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *provinceName;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CityInfo*> *cityListArray;
/// The number of items in @c cityListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger cityListArray_Count;

@end

#pragma mark - CityInfo

typedef GPB_ENUM(CityInfo_FieldNumber) {
  CityInfo_FieldNumber_CityId = 1,
  CityInfo_FieldNumber_CityName = 2,
  CityInfo_FieldNumber_CountyListArray = 3,
  CityInfo_FieldNumber_IsHotCity = 4,
};

@interface CityInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t cityId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cityName;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CountyInfo*> *countyListArray;
/// The number of items in @c countyListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger countyListArray_Count;

/// 0-非热门城市；>0-热门城市id
@property(nonatomic, readwrite) uint32_t isHotCity;

@end

#pragma mark - CountyInfo

typedef GPB_ENUM(CountyInfo_FieldNumber) {
  CountyInfo_FieldNumber_CountyId = 1,
  CountyInfo_FieldNumber_CountyName = 2,
  CountyInfo_FieldNumber_TownListArray = 3,
};

@interface CountyInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t countyId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *countyName;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TownInfo*> *townListArray;
/// The number of items in @c townListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger townListArray_Count;

@end

#pragma mark - TownInfo

typedef GPB_ENUM(TownInfo_FieldNumber) {
  TownInfo_FieldNumber_TownId = 1,
  TownInfo_FieldNumber_TownName = 2,
};

@interface TownInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t townId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *townName;

@end

#pragma mark - ProvinceDetailInfo

typedef GPB_ENUM(ProvinceDetailInfo_FieldNumber) {
  ProvinceDetailInfo_FieldNumber_ProvinceId = 1,
  ProvinceDetailInfo_FieldNumber_ProvinceName = 2,
};

@interface ProvinceDetailInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t provinceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *provinceName;

@end

#pragma mark - CityDetailInfo

typedef GPB_ENUM(CityDetailInfo_FieldNumber) {
  CityDetailInfo_FieldNumber_ProvinceId = 1,
  CityDetailInfo_FieldNumber_ProvinceName = 2,
  CityDetailInfo_FieldNumber_CityId = 3,
  CityDetailInfo_FieldNumber_CityName = 4,
};

@interface CityDetailInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t provinceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *provinceName;

@property(nonatomic, readwrite) uint32_t cityId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cityName;

@end

#pragma mark - CountyDetailInfo

typedef GPB_ENUM(CountyDetailInfo_FieldNumber) {
  CountyDetailInfo_FieldNumber_ProvinceId = 1,
  CountyDetailInfo_FieldNumber_ProvinceName = 2,
  CountyDetailInfo_FieldNumber_CityId = 3,
  CountyDetailInfo_FieldNumber_CityName = 4,
  CountyDetailInfo_FieldNumber_CountyId = 5,
  CountyDetailInfo_FieldNumber_CountyName = 6,
  CountyDetailInfo_FieldNumber_CityCode = 7,
};

@interface CountyDetailInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t provinceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *provinceName;

@property(nonatomic, readwrite) uint32_t cityId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cityName;

@property(nonatomic, readwrite) uint32_t countyId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *countyName;

@property(nonatomic, readwrite) uint32_t cityCode;

@end

#pragma mark - TownDetailInfo

typedef GPB_ENUM(TownDetailInfo_FieldNumber) {
  TownDetailInfo_FieldNumber_ProvinceId = 1,
  TownDetailInfo_FieldNumber_ProvinceName = 2,
  TownDetailInfo_FieldNumber_CityId = 3,
  TownDetailInfo_FieldNumber_CityName = 4,
  TownDetailInfo_FieldNumber_CountyId = 5,
  TownDetailInfo_FieldNumber_CountyName = 6,
  TownDetailInfo_FieldNumber_TownId = 7,
  TownDetailInfo_FieldNumber_TownName = 8,
};

@interface TownDetailInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t provinceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *provinceName;

@property(nonatomic, readwrite) uint32_t cityId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cityName;

@property(nonatomic, readwrite) uint32_t countyId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *countyName;

@property(nonatomic, readwrite) uint32_t townId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *townName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
