// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum STAT_TYPE

typedef GPB_ENUM(STAT_TYPE) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  STAT_TYPE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  STAT_TYPE_StDefault = 0,

  ///用户行为统计
  STAT_TYPE_StUserAction = 1,

  ///统计接口
  STAT_TYPE_StInterFace = 2,
};

GPBEnumDescriptor *STAT_TYPE_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL STAT_TYPE_IsValidValue(int32_t value);

#pragma mark - Enum ACTION

typedef GPB_ENUM(ACTION) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  ACTION_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ACTION_ActDefault = 0,

  ///页面浏览曝光
  ACTION_ActView = 100,

  ///点击
  ACTION_ActClick = 200,

  ///分享
  ACTION_ActShare = 300,

  ///举报
  ACTION_ActReport = 400,
};

GPBEnumDescriptor *ACTION_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL ACTION_IsValidValue(int32_t value);

#pragma mark - Enum SCENCE_PAGE

typedef GPB_ENUM(SCENCE_PAGE) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  SCENCE_PAGE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SCENCE_PAGE_SpDefault = 0,

  ///闪屏
  SCENCE_PAGE_SpSplash = 1,

  ///登录主界面
  SCENCE_PAGE_SpLogin = 2,

  ///手机号登录界面
  SCENCE_PAGE_SpLoginPhone = 3,

  ///完善个人资料
  SCENCE_PAGE_SpCompleteProfile = 4,

  ///编辑头像
  SCENCE_PAGE_SpEditFace = 5,

  ///添加宠物
  SCENCE_PAGE_SpAddPet = 6,

  ///推荐用户
  SCENCE_PAGE_SpRecommandUser = 7,

  ///附近的人
  SCENCE_PAGE_SpNear = 8,

  ///他人主页
  SCENCE_PAGE_SpUserProfile = 9,

  ///遛狗
  SCENCE_PAGE_SpWalkdog = 10,

  ///Feeds列表页
  SCENCE_PAGE_SpFeeds = 11,

  ///Feeds详情页
  SCENCE_PAGE_SpFeedsDetail = 12,

  ///Feeds添加页
  SCENCE_PAGE_SpFeedsAdd = 13,
};

GPBEnumDescriptor *SCENCE_PAGE_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL SCENCE_PAGE_IsValidValue(int32_t value);

#pragma mark - StatRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface StatRoot : GPBRootObject
@end

#pragma mark - StatUserAction

typedef GPB_ENUM(StatUserAction_FieldNumber) {
  StatUserAction_FieldNumber_SourceScene = 1,
  StatUserAction_FieldNumber_Scene = 2,
  StatUserAction_FieldNumber_Slot = 3,
  StatUserAction_FieldNumber_Action = 4,
  StatUserAction_FieldNumber_UserId = 5,
  StatUserAction_FieldNumber_SceneKey = 6,
  StatUserAction_FieldNumber_ExtraData = 7,
  StatUserAction_FieldNumber_Time = 8,
  StatUserAction_FieldNumber_PushId = 9,
  StatUserAction_FieldNumber_Result = 10,
};

@interface StatUserAction : GPBMessage

///源场景 见enum SCENCE_PAGE
@property(nonatomic, readwrite) uint32_t sourceScene;

///场景 见enum SCENCE_PAGE
@property(nonatomic, readwrite) uint32_t scene;

///槽位号
@property(nonatomic, readwrite, copy, null_resettable) NSString *slot;

///动作 见enum ACTION
@property(nonatomic, readwrite) uint32_t action;

///用户ID 未登录 0
@property(nonatomic, readwrite) uint64_t userId;

///当前页面主键  用户详情页为用户ID，帖子详情页为帖子ID，宠物详情页为宠物ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *sceneKey;

///额外数据
@property(nonatomic, readwrite, copy, null_resettable) NSString *extraData;

///时间
@property(nonatomic, readwrite) uint64_t time;

///pushId
@property(nonatomic, readwrite) uint64_t pushId;

///结果
@property(nonatomic, readwrite) uint32_t result;

@end

#pragma mark - StatInterFace

typedef GPB_ENUM(StatInterFace_FieldNumber) {
  StatInterFace_FieldNumber_UserId = 1,
  StatInterFace_FieldNumber_Method = 2,
  StatInterFace_FieldNumber_MethodKey = 3,
  StatInterFace_FieldNumber_Result = 4,
  StatInterFace_FieldNumber_CostTime = 5,
  StatInterFace_FieldNumber_ExtraData = 6,
};

@interface StatInterFace : GPBMessage

///当前登录用户ID 未登录 0
@property(nonatomic, readwrite) uint64_t userId;

///调用方法
@property(nonatomic, readwrite, copy, null_resettable) NSString *method;

///发发主键
@property(nonatomic, readwrite, copy, null_resettable) NSString *methodKey;

///结果
@property(nonatomic, readwrite) uint32_t result;

///耗时
@property(nonatomic, readwrite) uint32_t costTime;

///额外数据
@property(nonatomic, readwrite, copy, null_resettable) NSString *extraData;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
