// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Insure.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - InsureRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface InsureRoot : GPBRootObject
@end

#pragma mark - TendDetailType

typedef GPB_ENUM(TendDetailType_FieldNumber) {
  TendDetailType_FieldNumber_Id_p = 1,
  TendDetailType_FieldNumber_TypeName = 2,
  TendDetailType_FieldNumber_Remark = 3,
  TendDetailType_FieldNumber_Status = 4,
  TendDetailType_FieldNumber_CreateStaffId = 5,
  TendDetailType_FieldNumber_CreateStaffName = 6,
  TendDetailType_FieldNumber_CreateTime = 7,
  TendDetailType_FieldNumber_CompanyId = 8,
};

/// 照护明细类型
@interface TendDetailType : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 类型名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeName;

/// 备注
@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

/// 状态 0-正常 -1-已删除
@property(nonatomic, readwrite) int32_t status;

/// 创建员工ID
@property(nonatomic, readwrite) uint64_t createStaffId;

/// 创建员工名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *createStaffName;

/// 创建时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 公司id
@property(nonatomic, readwrite) uint64_t companyId;

@end

#pragma mark - Illness

typedef GPB_ENUM(Illness_FieldNumber) {
  Illness_FieldNumber_Id_p = 1,
  Illness_FieldNumber_IllnessName = 2,
  Illness_FieldNumber_Remark = 3,
  Illness_FieldNumber_Status = 4,
  Illness_FieldNumber_CreateStaffId = 5,
  Illness_FieldNumber_CreateStaffName = 6,
  Illness_FieldNumber_CreateTime = 7,
  Illness_FieldNumber_CompanyId = 8,
};

/// 病症
@interface Illness : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 病症名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *illnessName;

/// 备注
@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

/// 状态 0-正常 -1-已删除
@property(nonatomic, readwrite) int32_t status;

/// 创建员工ID
@property(nonatomic, readwrite) uint64_t createStaffId;

/// 创建员工名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *createStaffName;

/// 创建时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 公司id
@property(nonatomic, readwrite) uint64_t companyId;

@end

#pragma mark - TendDetail

typedef GPB_ENUM(TendDetail_FieldNumber) {
  TendDetail_FieldNumber_Id_p = 1,
  TendDetail_FieldNumber_TendDetail = 2,
  TendDetail_FieldNumber_DetailTypeId = 3,
  TendDetail_FieldNumber_DetailTypeName = 4,
  TendDetail_FieldNumber_IllnessId = 5,
  TendDetail_FieldNumber_IllnessName = 6,
  TendDetail_FieldNumber_Status = 7,
  TendDetail_FieldNumber_CreateStaffId = 8,
  TendDetail_FieldNumber_CreateStaffName = 9,
  TendDetail_FieldNumber_CreateTime = 10,
  TendDetail_FieldNumber_CompanyId = 11,
};

/// 照护明细
@interface TendDetail : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 照护明细内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *tendDetail;

/// 照护明细类型id
@property(nonatomic, readwrite) uint64_t detailTypeId;

/// 照护明细类型名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *detailTypeName;

/// 适用病症id
@property(nonatomic, readwrite) uint64_t illnessId;

/// 病症名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *illnessName;

/// 状态 0-正常 -1-已删除
@property(nonatomic, readwrite) int32_t status;

/// 创建员工ID
@property(nonatomic, readwrite) uint64_t createStaffId;

/// 创建员工名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *createStaffName;

/// 创建时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 公司id
@property(nonatomic, readwrite) uint64_t companyId;

@end

#pragma mark - InsureListVO

typedef GPB_ENUM(InsureListVO_FieldNumber) {
  InsureListVO_FieldNumber_InsureNo = 1,
  InsureListVO_FieldNumber_KinsName = 2,
  InsureListVO_FieldNumber_Idcard = 3,
  InsureListVO_FieldNumber_ContactName = 4,
  InsureListVO_FieldNumber_ContactPhone = 5,
  InsureListVO_FieldNumber_AddrDetail = 6,
  InsureListVO_FieldNumber_StatusStr = 7,
  InsureListVO_FieldNumber_Status = 8,
  InsureListVO_FieldNumber_OrderStatusStr = 9,
  InsureListVO_FieldNumber_OrderStatus = 10,
};

/// 申请单列表的VO
@interface InsureListVO : GPBMessage

/// 申请单号
@property(nonatomic, readwrite, copy, null_resettable) NSString *insureNo;

/// 被陪护人名字
@property(nonatomic, readwrite, copy, null_resettable) NSString *kinsName;

/// 被陪护人身份证号
@property(nonatomic, readwrite, copy, null_resettable) NSString *idcard;

/// 联系人
@property(nonatomic, readwrite, copy, null_resettable) NSString *contactName;

/// 联系人手机号
@property(nonatomic, readwrite, copy, null_resettable) NSString *contactPhone;

/// 联系地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *addrDetail;

/// 状态描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *statusStr;

/// 状态
@property(nonatomic, readwrite) int32_t status;

/// 下单意愿
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderStatusStr;

/// 下单意愿 0-未联系 1-暂不下单 2-等待下单 3-已下单
@property(nonatomic, readwrite) uint32_t orderStatus;

@end

#pragma mark - SubsidyVO

typedef GPB_ENUM(SubsidyVO_FieldNumber) {
  SubsidyVO_FieldNumber_MonthDesc = 1,
  SubsidyVO_FieldNumber_AmountStr = 2,
  SubsidyVO_FieldNumber_SubsidyDesc = 3,
  SubsidyVO_FieldNumber_Amount = 4,
  SubsidyVO_FieldNumber_Ym = 5,
  SubsidyVO_FieldNumber_Days = 6,
  SubsidyVO_FieldNumber_Unit = 7,
};

/// 补贴明细VO
@interface SubsidyVO : GPBMessage

/// 月份描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *monthDesc;

/// 金额
@property(nonatomic, readwrite, copy, null_resettable) NSString *amountStr;

/// 补贴明细
@property(nonatomic, readwrite, copy, null_resettable) NSString *subsidyDesc;

@property(nonatomic, readwrite) uint64_t amount;

/// 年月
@property(nonatomic, readwrite, copy, null_resettable) NSString *ym;

/// 天数
@property(nonatomic, readwrite) uint32_t days;

/// 单位
@property(nonatomic, readwrite) uint32_t unit;

@end

#pragma mark - TeachRecordVO

typedef GPB_ENUM(TeachRecordVO_FieldNumber) {
  TeachRecordVO_FieldNumber_OrderId = 1,
  TeachRecordVO_FieldNumber_RecordId = 2,
  TeachRecordVO_FieldNumber_CreateDate = 3,
  TeachRecordVO_FieldNumber_HgPraise = 4,
};

/// 带教记录VO
@interface TeachRecordVO : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite) uint64_t recordId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hgPraise;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
