// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 #import "comm/Err.pbobjc.h"
 #import "comm/Area.pbobjc.h"
 #import "comm/Comm.pbobjc.h"
 #import "comm/Lbs.pbobjc.h"
 #import "Cmd.pbobjc.h"
 #import "CommonData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AppError;
@class LbsData;
@class PkgInfo;
@class ReqHead;
@class RequestItem;
@class ResponseItem;
@class RspHead;
@class StatReportItem;
@class Terminal;
GPB_ENUM_FWD_DECLARE(APP_COMMAND);
GPB_ENUM_FWD_DECLARE(APP_ERROR_CODE);
GPB_ENUM_FWD_DECLARE(NET_TYPE);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - InterfaceRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface InterfaceRoot : GPBRootObject
@end

#pragma mark - AppError

typedef GPB_ENUM(AppError_FieldNumber) {
  AppError_FieldNumber_ErrorCode = 1,
  AppError_FieldNumber_Msg = 2,
};

///*
/// 返回错误信息
@interface AppError : GPBMessage

@property(nonatomic, readwrite) enum APP_ERROR_CODE errorCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@end

/// Fetches the raw value of a @c AppError's @c errorCode property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t AppError_ErrorCode_RawValue(AppError *message);
/// Sets the raw value of an @c AppError's @c errorCode property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetAppError_ErrorCode_RawValue(AppError *message, int32_t value);

#pragma mark - ReqHead

typedef GPB_ENUM(ReqHead_FieldNumber) {
  ReqHead_FieldNumber_Yua = 1,
  ReqHead_FieldNumber_Guid = 2,
  ReqHead_FieldNumber_Sid = 3,
  ReqHead_FieldNumber_Terminal = 4,
  ReqHead_FieldNumber_NetType = 5,
  ReqHead_FieldNumber_Pkginfo = 6,
};

///请求包头
@interface ReqHead : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *yua;

@property(nonatomic, readwrite, copy, null_resettable) NSString *guid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sid;

@property(nonatomic, readwrite, strong, null_resettable) Terminal *terminal;
/// Test to see if @c terminal has been set.
@property(nonatomic, readwrite) BOOL hasTerminal;

@property(nonatomic, readwrite) enum NET_TYPE netType;

@property(nonatomic, readwrite, strong, null_resettable) PkgInfo *pkginfo;
/// Test to see if @c pkginfo has been set.
@property(nonatomic, readwrite) BOOL hasPkginfo;

@end

/// Fetches the raw value of a @c ReqHead's @c netType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t ReqHead_NetType_RawValue(ReqHead *message);
/// Sets the raw value of an @c ReqHead's @c netType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetReqHead_NetType_RawValue(ReqHead *message, int32_t value);

#pragma mark - RequestItem

typedef GPB_ENUM(RequestItem_FieldNumber) {
  RequestItem_FieldNumber_Command = 1,
  RequestItem_FieldNumber_Encrypt = 2,
  RequestItem_FieldNumber_BinBody = 3,
};

@interface RequestItem : GPBMessage

/// 服务端命令号
@property(nonatomic, readwrite) enum APP_COMMAND command;

///加密方式[1:未加密，2：DES加密]
@property(nonatomic, readwrite) uint32_t encrypt;

/// 请求数据
@property(nonatomic, readwrite, copy, null_resettable) NSData *binBody;

@end

/// Fetches the raw value of a @c RequestItem's @c command property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t RequestItem_Command_RawValue(RequestItem *message);
/// Sets the raw value of an @c RequestItem's @c command property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetRequestItem_Command_RawValue(RequestItem *message, int32_t value);

#pragma mark - AppRequest

typedef GPB_ENUM(AppRequest_FieldNumber) {
  AppRequest_FieldNumber_Head = 1,
  AppRequest_FieldNumber_GpsInfo = 2,
  AppRequest_FieldNumber_RequestId = 3,
  AppRequest_FieldNumber_Version = 4,
  AppRequest_FieldNumber_ReqsArray = 5,
};

@interface AppRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ReqHead *head;
/// Test to see if @c head has been set.
@property(nonatomic, readwrite) BOOL hasHead;

///lbs原始信息
@property(nonatomic, readwrite, strong, null_resettable) LbsData *gpsInfo;
/// Test to see if @c gpsInfo has been set.
@property(nonatomic, readwrite) BOOL hasGpsInfo;

///请求序列号，需要在Response中返回
@property(nonatomic, readwrite) uint32_t requestId;

///表明当前协议的版本号
@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RequestItem*> *reqsArray;
/// The number of items in @c reqsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger reqsArray_Count;

@end

#pragma mark - RspHead

typedef GPB_ENUM(RspHead_FieldNumber) {
  RspHead_FieldNumber_Guid = 1,
  RspHead_FieldNumber_Sid = 2,
};

///回包包头
@interface RspHead : GPBMessage

///在需要客户端重置GUID的时候返回
@property(nonatomic, readwrite, copy, null_resettable) NSString *guid;

///在需要客户端更换SID的时候保存
@property(nonatomic, readwrite, copy, null_resettable) NSString *sid;

@end

#pragma mark - ResponseItem

typedef GPB_ENUM(ResponseItem_FieldNumber) {
  ResponseItem_FieldNumber_Command = 1,
  ResponseItem_FieldNumber_Encrypt = 2,
  ResponseItem_FieldNumber_Err = 3,
  ResponseItem_FieldNumber_BinBody = 4,
};

@interface ResponseItem : GPBMessage

/// 服务端命令号
@property(nonatomic, readwrite) enum APP_COMMAND command;

///加密方式[1:未加密，2：DES加密]
@property(nonatomic, readwrite) uint32_t encrypt;

@property(nonatomic, readwrite, strong, null_resettable) AppError *err;
/// Test to see if @c err has been set.
@property(nonatomic, readwrite) BOOL hasErr;

@property(nonatomic, readwrite, copy, null_resettable) NSData *binBody;

@end

/// Fetches the raw value of a @c ResponseItem's @c command property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t ResponseItem_Command_RawValue(ResponseItem *message);
/// Sets the raw value of an @c ResponseItem's @c command property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetResponseItem_Command_RawValue(ResponseItem *message, int32_t value);

#pragma mark - AppResponse

typedef GPB_ENUM(AppResponse_FieldNumber) {
  AppResponse_FieldNumber_Head = 1,
  AppResponse_FieldNumber_ErrInfo = 2,
  AppResponse_FieldNumber_RequestId = 3,
  AppResponse_FieldNumber_SysTimeStamp = 4,
  AppResponse_FieldNumber_RspsArray = 5,
};

@interface AppResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RspHead *head;
/// Test to see if @c head has been set.
@property(nonatomic, readwrite) BOOL hasHead;

///框架级别的错误码，只有当该错误码为APP_ERROR_CODE.AEC_SUCCESS的时候，binBody中的数据才有意义
@property(nonatomic, readwrite, strong, null_resettable) AppError *errInfo;
/// Test to see if @c errInfo has been set.
@property(nonatomic, readwrite) BOOL hasErrInfo;

///请求序列号，与对应的请求中的RequestId相同
@property(nonatomic, readwrite) uint32_t requestId;

/// 服务器时间戳
@property(nonatomic, readwrite) uint64_t sysTimeStamp;

/// 返回数据
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ResponseItem*> *rspsArray;
/// The number of items in @c rspsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger rspsArray_Count;

@end

#pragma mark - PingReq

typedef GPB_ENUM(PingReq_FieldNumber) {
  PingReq_FieldNumber_Str = 1,
};

///Ping 请求  原样返回请求字符串
@interface PingReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *str;

@end

#pragma mark - PingRsp

typedef GPB_ENUM(PingRsp_FieldNumber) {
  PingRsp_FieldNumber_Str = 1,
};

@interface PingRsp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *str;

@end

#pragma mark - UploadImageRsp

typedef GPB_ENUM(UploadImageRsp_FieldNumber) {
  UploadImageRsp_FieldNumber_Code = 1,
  UploadImageRsp_FieldNumber_Msg = 2,
  UploadImageRsp_FieldNumber_ImgId = 3,
};

@interface UploadImageRsp : GPBMessage

@property(nonatomic, readwrite) uint32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite) uint64_t imgId;

@end

#pragma mark - UploadExcelRsp

typedef GPB_ENUM(UploadExcelRsp_FieldNumber) {
  UploadExcelRsp_FieldNumber_Code = 1,
  UploadExcelRsp_FieldNumber_Msg = 2,
  UploadExcelRsp_FieldNumber_ExcelURL = 3,
};

@interface UploadExcelRsp : GPBMessage

@property(nonatomic, readwrite) uint32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *excelURL;

@end

#pragma mark - StatReportReq

typedef GPB_ENUM(StatReportReq_FieldNumber) {
  StatReportReq_FieldNumber_ItemsArray = 1,
};

///统计上报
@interface StatReportReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<StatReportItem*> *itemsArray;
/// The number of items in @c itemsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - StatReportRsp

typedef GPB_ENUM(StatReportRsp_FieldNumber) {
  StatReportRsp_FieldNumber_Ret = 1,
};

@interface StatReportRsp : GPBMessage

///版本号
@property(nonatomic, readwrite) uint32_t ret;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
