// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Model.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class WXMenuInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ModelRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ModelRoot : GPBRootObject
@end

#pragma mark - ImageModel

typedef GPB_ENUM(ImageModel_FieldNumber) {
  ImageModel_FieldNumber_ImageId = 1,
  ImageModel_FieldNumber_Type = 2,
  ImageModel_FieldNumber_Suffix = 3,
  ImageModel_FieldNumber_Width = 4,
  ImageModel_FieldNumber_Height = 5,
  ImageModel_FieldNumber_Bgcolor = 6,
  ImageModel_FieldNumber_Longitude = 7,
  ImageModel_FieldNumber_Latitude = 8,
  ImageModel_FieldNumber_CenterX = 9,
  ImageModel_FieldNumber_CenterY = 10,
  ImageModel_FieldNumber_CreateTime = 11,
};

@interface ImageModel : GPBMessage

@property(nonatomic, readwrite) uint64_t imageId;

/// 图片类型
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/// 后缀
@property(nonatomic, readwrite, copy, null_resettable) NSString *suffix;

/// 图片宽度
@property(nonatomic, readwrite) uint32_t width;

/// 图片高度
@property(nonatomic, readwrite) uint32_t height;

/// 背景色
@property(nonatomic, readwrite) uint32_t bgcolor;

/// 图片位置经度
@property(nonatomic, readwrite) double longitude;

/// 图片位置纬度
@property(nonatomic, readwrite) double latitude;

/// 图片中心点
@property(nonatomic, readwrite) double centerX;

@property(nonatomic, readwrite) double centerY;

/// 上传时间
@property(nonatomic, readwrite) uint64_t createTime;

@end

#pragma mark - UserModel

typedef GPB_ENUM(UserModel_FieldNumber) {
  UserModel_FieldNumber_Id_p = 1,
  UserModel_FieldNumber_Name = 2,
  UserModel_FieldNumber_Sex = 3,
  UserModel_FieldNumber_NickName = 4,
  UserModel_FieldNumber_Birthday = 5,
  UserModel_FieldNumber_Phone = 6,
  UserModel_FieldNumber_HeadImg = 7,
  UserModel_FieldNumber_State = 8,
  UserModel_FieldNumber_ChannelId = 9,
  UserModel_FieldNumber_Address = 10,
  UserModel_FieldNumber_Adcode = 11,
  UserModel_FieldNumber_ProvinceId = 12,
  UserModel_FieldNumber_CityId = 13,
  UserModel_FieldNumber_Province = 14,
  UserModel_FieldNumber_City = 15,
  UserModel_FieldNumber_County = 16,
  UserModel_FieldNumber_Building = 17,
  UserModel_FieldNumber_Lat = 18,
  UserModel_FieldNumber_Lng = 19,
  UserModel_FieldNumber_RongCloudToken = 20,
  UserModel_FieldNumber_Remark = 21,
  UserModel_FieldNumber_CreateTime = 22,
  UserModel_FieldNumber_UpdateTime = 23,
  UserModel_FieldNumber_LastTime = 24,
  UserModel_FieldNumber_ActiveState = 25,
  UserModel_FieldNumber_WxNo = 26,
  UserModel_FieldNumber_QqNo = 27,
  UserModel_FieldNumber_Email = 28,
  UserModel_FieldNumber_FirstTime = 29,
  UserModel_FieldNumber_Diffno = 30,
  UserModel_FieldNumber_RealName = 31,
  UserModel_FieldNumber_Idcard = 32,
};

@interface UserModel : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) uint32_t sex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *birthday;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *headImg;

/// 用户状态：0-正常，-1-删除
@property(nonatomic, readwrite) uint32_t state;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite) uint64_t adcode;

@property(nonatomic, readwrite) uint64_t provinceId;

@property(nonatomic, readwrite) uint64_t cityId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *province;

@property(nonatomic, readwrite, copy, null_resettable) NSString *city;

@property(nonatomic, readwrite, copy, null_resettable) NSString *county;

@property(nonatomic, readwrite, copy, null_resettable) NSString *building;

@property(nonatomic, readwrite) double lat;

@property(nonatomic, readwrite) double lng;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rongCloudToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

@property(nonatomic, readwrite) uint64_t createTime;

@property(nonatomic, readwrite) uint64_t updateTime;

@property(nonatomic, readwrite) uint64_t lastTime;

///用户活跃状态 1 - 未登录 2 - 登录.
@property(nonatomic, readwrite) uint32_t activeState;

/// 微信号
@property(nonatomic, readwrite, copy, null_resettable) NSString *wxNo;

/// qq号
@property(nonatomic, readwrite, copy, null_resettable) NSString *qqNo;

/// 电子邮箱
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

/// 首次绑定手机号时间
@property(nonatomic, readwrite) uint64_t firstTime;

/// 异号（针对于没有手机号的一些用户）
@property(nonatomic, readwrite, copy, null_resettable) NSString *diffno;

/// 实名制姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

/// 身份证号
@property(nonatomic, readwrite, copy, null_resettable) NSString *idcard;

@end

#pragma mark - WXMsgInfo

typedef GPB_ENUM(WXMsgInfo_FieldNumber) {
  WXMsgInfo_FieldNumber_CmdId = 1,
  WXMsgInfo_FieldNumber_Keyword = 2,
  WXMsgInfo_FieldNumber_Msg = 3,
  WXMsgInfo_FieldNumber_CreateTime = 4,
  WXMsgInfo_FieldNumber_Editor = 5,
  WXMsgInfo_FieldNumber_MsgType = 6,
  WXMsgInfo_FieldNumber_CreateStaffId = 7,
  WXMsgInfo_FieldNumber_CreateStaffName = 8,
  WXMsgInfo_FieldNumber_UpdateTime = 9,
  WXMsgInfo_FieldNumber_UpdateStaffId = 10,
  WXMsgInfo_FieldNumber_UpdateStaffName = 11,
};

@interface WXMsgInfo : GPBMessage

/// id
@property(nonatomic, readwrite) uint32_t cmdId;

/// 关键字 
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

/// 回复内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

/// 创建时间
@property(nonatomic, readwrite) uint64_t createTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *editor;

/// 类型 1-文字消息 2-图片消息
@property(nonatomic, readwrite) uint32_t msgType;

/// 创建员工ID
@property(nonatomic, readwrite) uint64_t createStaffId;

/// 创建员工名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *createStaffName;

/// 创建时间
@property(nonatomic, readwrite) uint64_t updateTime;

/// 创建员工ID
@property(nonatomic, readwrite) uint64_t updateStaffId;

/// 创建员工名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *updateStaffName;

@end

#pragma mark - WXMenuInfo

typedef GPB_ENUM(WXMenuInfo_FieldNumber) {
  WXMenuInfo_FieldNumber_MenuId = 1,
  WXMenuInfo_FieldNumber_ParentId = 2,
  WXMenuInfo_FieldNumber_MenuName = 3,
  WXMenuInfo_FieldNumber_MenuType = 4,
  WXMenuInfo_FieldNumber_MenuURL = 6,
  WXMenuInfo_FieldNumber_MenuMsg = 7,
  WXMenuInfo_FieldNumber_CreateTime = 8,
  WXMenuInfo_FieldNumber_Editor = 9,
  WXMenuInfo_FieldNumber_SubMenusArray = 10,
  WXMenuInfo_FieldNumber_State = 11,
};

@interface WXMenuInfo : GPBMessage

///	主键id
@property(nonatomic, readwrite) uint64_t menuId;

///	父节点id
@property(nonatomic, readwrite) uint64_t parentId;

///	菜单名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *menuName;

///   菜单类型
@property(nonatomic, readwrite) uint32_t menuType;

///	菜单链接
@property(nonatomic, readwrite, copy, null_resettable) NSString *menuURL;

///   菜单消息
@property(nonatomic, readwrite, copy, null_resettable) NSString *menuMsg;

///   创建时间
@property(nonatomic, readwrite) uint64_t createTime;

///	修改者
@property(nonatomic, readwrite, copy, null_resettable) NSString *editor;

///		微信菜单详情
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<WXMenuInfo*> *subMenusArray;
/// The number of items in @c subMenusArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger subMenusArray_Count;

///   状态,  1:正常状态,可以显示   0:删除状态,不予显示
@property(nonatomic, readwrite) uint32_t state;

@end

#pragma mark - WXMPUserInfo

typedef GPB_ENUM(WXMPUserInfo_FieldNumber) {
  WXMPUserInfo_FieldNumber_OpenId = 1,
  WXMPUserInfo_FieldNumber_Unionid = 2,
  WXMPUserInfo_FieldNumber_UserId = 3,
  WXMPUserInfo_FieldNumber_ActType = 4,
  WXMPUserInfo_FieldNumber_ChannelId = 5,
  WXMPUserInfo_FieldNumber_CreateTime = 6,
};

@interface WXMPUserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *openId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *unionid;

@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) uint32_t actType;

@property(nonatomic, readwrite) uint32_t channelId;

@property(nonatomic, readwrite) uint64_t createTime;

@end

#pragma mark - WXUser

typedef GPB_ENUM(WXUser_FieldNumber) {
  WXUser_FieldNumber_UserId = 1,
  WXUser_FieldNumber_ThirdType = 2,
  WXUser_FieldNumber_WxAppId = 3,
  WXUser_FieldNumber_OpenId = 4,
  WXUser_FieldNumber_Unionid = 5,
  WXUser_FieldNumber_AccessKey = 6,
  WXUser_FieldNumber_RefreshKey = 7,
  WXUser_FieldNumber_ExpiresTime = 8,
  WXUser_FieldNumber_NickName = 9,
  WXUser_FieldNumber_HeadImg = 10,
  WXUser_FieldNumber_Sex = 11,
  WXUser_FieldNumber_CreateTime = 12,
  WXUser_FieldNumber_ChannelId = 13,
};

@interface WXUser : GPBMessage

@property(nonatomic, readwrite) uint64_t userId;

/// 1：微信；2：QQ；3：新浪微博；4:微信公众号
@property(nonatomic, readwrite) int32_t thirdType;

/// 微信公众号开放平台appid
@property(nonatomic, readwrite, copy, null_resettable) NSString *wxAppId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *openId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *unionid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *refreshKey;

@property(nonatomic, readwrite) uint64_t expiresTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *headImg;

/// 1-男 2-女
@property(nonatomic, readwrite) uint32_t sex;

@property(nonatomic, readwrite) uint64_t createTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@end

#pragma mark - BannerModel

typedef GPB_ENUM(BannerModel_FieldNumber) {
  BannerModel_FieldNumber_Id_p = 1,
  BannerModel_FieldNumber_Name = 2,
  BannerModel_FieldNumber_BannerType = 3,
  BannerModel_FieldNumber_URL = 4,
  BannerModel_FieldNumber_ImgURL = 5,
  BannerModel_FieldNumber_Desc = 6,
  BannerModel_FieldNumber_StartDate = 7,
  BannerModel_FieldNumber_EndDate = 8,
  BannerModel_FieldNumber_Editor = 11,
  BannerModel_FieldNumber_CreateTime = 12,
  BannerModel_FieldNumber_ImgId = 13,
  BannerModel_FieldNumber_Sort = 14,
};

@interface BannerModel : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

///  banner名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

///  类型 1-微信banner 2-用户app banner
@property(nonatomic, readwrite) uint32_t bannerType;

///  跳转路径
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

///  图片路径或图片id
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgURL;

///  banner描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

///  开始时间
@property(nonatomic, readwrite) uint64_t startDate;

///  结束时间
@property(nonatomic, readwrite) uint64_t endDate;

///  创建者
@property(nonatomic, readwrite, copy, null_resettable) NSString *editor;

///  创建时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 图片id
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgId;

/// banner排序
@property(nonatomic, readwrite) uint32_t sort;

@end

#pragma mark - SplashScreenModel

typedef GPB_ENUM(SplashScreenModel_FieldNumber) {
  SplashScreenModel_FieldNumber_Id_p = 1,
  SplashScreenModel_FieldNumber_Name = 2,
  SplashScreenModel_FieldNumber_Duration = 3,
  SplashScreenModel_FieldNumber_Type = 4,
  SplashScreenModel_FieldNumber_URL = 5,
  SplashScreenModel_FieldNumber_ImgURL = 6,
  SplashScreenModel_FieldNumber_Desc = 7,
  SplashScreenModel_FieldNumber_StartDate = 8,
  SplashScreenModel_FieldNumber_EndDate = 9,
  SplashScreenModel_FieldNumber_Editor = 11,
  SplashScreenModel_FieldNumber_CreateTime = 12,
  SplashScreenModel_FieldNumber_ImgId = 13,
};

///  闪屏model
@interface SplashScreenModel : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

///  闪屏名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

///  持续的时间（秒）
@property(nonatomic, readwrite) uint32_t duration;

///  类型 1-用户app 2-护工app
@property(nonatomic, readwrite) uint32_t type;

///  跳转路径
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

///  图片路径或图片id
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgURL;

///  描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

///  开始时间
@property(nonatomic, readwrite) uint64_t startDate;

///  结束时间
@property(nonatomic, readwrite) uint64_t endDate;

///  创建者
@property(nonatomic, readwrite, copy, null_resettable) NSString *editor;

///  创建时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 图片id
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgId;

@end

#pragma mark - AppVersion

typedef GPB_ENUM(AppVersion_FieldNumber) {
  AppVersion_FieldNumber_Id_p = 1,
  AppVersion_FieldNumber_Name = 2,
  AppVersion_FieldNumber_Version = 3,
  AppVersion_FieldNumber_Type = 4,
  AppVersion_FieldNumber_Platform = 5,
  AppVersion_FieldNumber_SourceLink = 6,
  AppVersion_FieldNumber_RemindLevel = 7,
  AppVersion_FieldNumber_PublishTime = 8,
  AppVersion_FieldNumber_RemindTime = 9,
  AppVersion_FieldNumber_Enabled = 10,
};

@interface AppVersion : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) uint32_t version;

///  APP类型 1-用户APP,2-企业APP
@property(nonatomic, readwrite) uint32_t type;

///  运行平台 1-ios, 2-android
@property(nonatomic, readwrite) uint32_t platform;

///  下载链接
@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceLink;

///  提醒级别 1 - 强制更新 2 - 推荐更新(重启APP提醒) 3 - 建议更新(只提醒一次)
@property(nonatomic, readwrite) uint32_t remindLevel;

///  发布时间
@property(nonatomic, readwrite) uint64_t publishTime;

///  提醒时间
@property(nonatomic, readwrite) uint64_t remindTime;

///  是否可用 1-可用 2-不可用
@property(nonatomic, readwrite) uint32_t enabled;

@end

#pragma mark - CouponTemplate

typedef GPB_ENUM(CouponTemplate_FieldNumber) {
  CouponTemplate_FieldNumber_Id_p = 1,
  CouponTemplate_FieldNumber_CouponCode = 2,
  CouponTemplate_FieldNumber_CouponName = 3,
  CouponTemplate_FieldNumber_CouponType = 4,
  CouponTemplate_FieldNumber_Fee = 5,
  CouponTemplate_FieldNumber_CouponDesc = 6,
  CouponTemplate_FieldNumber_PeriodType = 7,
  CouponTemplate_FieldNumber_StartDate = 8,
  CouponTemplate_FieldNumber_EndDate = 9,
  CouponTemplate_FieldNumber_ValidDays = 10,
  CouponTemplate_FieldNumber_Scence = 11,
  CouponTemplate_FieldNumber_ServiceTypesArray = 12,
  CouponTemplate_FieldNumber_OrgIdsArray = 13,
  CouponTemplate_FieldNumber_BranchIdsArray = 14,
  CouponTemplate_FieldNumber_Weekday = 15,
  CouponTemplate_FieldNumber_Weekend = 16,
  CouponTemplate_FieldNumber_Holiday = 17,
  CouponTemplate_FieldNumber_GetMaxNum = 18,
  CouponTemplate_FieldNumber_SendMaxNum = 19,
  CouponTemplate_FieldNumber_CompanyId = 20,
  CouponTemplate_FieldNumber_CompanyName = 21,
  CouponTemplate_FieldNumber_CreateStaffId = 22,
  CouponTemplate_FieldNumber_CreateStaffName = 23,
  CouponTemplate_FieldNumber_CreateTime = 24,
};

/// 优惠券模板
@interface CouponTemplate : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 优惠码
@property(nonatomic, readwrite, copy, null_resettable) NSString *couponCode;

/// 优惠券名
@property(nonatomic, readwrite, copy, null_resettable) NSString *couponName;

/// 优惠类型 1-减免 2-打折
@property(nonatomic, readwrite) uint32_t couponType;

/// 优惠额度 如果是减免就是减免的金额， 如果是打折90代表9折
@property(nonatomic, readwrite) uint32_t fee;

/// 优惠券描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *couponDesc;

/// 有效期类型 1-固定日期 2-有效天数
@property(nonatomic, readwrite) uint32_t periodType;

/// 开始日期
@property(nonatomic, readwrite, copy, null_resettable) NSString *startDate;

/// 结束日期
@property(nonatomic, readwrite, copy, null_resettable) NSString *endDate;

/// 有效天数
@property(nonatomic, readwrite) uint32_t validDays;

/// 适用场景 1-机构 2-居家
@property(nonatomic, readwrite) uint32_t scence;

/// 限定服务类型，机构有1-1 1-n，居家有中医理疗等
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *serviceTypesArray;
/// The number of items in @c serviceTypesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger serviceTypesArray_Count;

/// 限定机构id
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *orgIdsArray;
/// The number of items in @c orgIdsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger orgIdsArray_Count;

/// 限定科室id
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *branchIdsArray;
/// The number of items in @c branchIdsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger branchIdsArray_Count;

/// 是否工作日可用
@property(nonatomic, readwrite) uint32_t weekday;

/// 是否周末可用
@property(nonatomic, readwrite) uint32_t weekend;

/// 是否节假日可用
@property(nonatomic, readwrite) uint32_t holiday;

/// 可领取最大数量
@property(nonatomic, readwrite) uint32_t getMaxNum;

/// 可发送最大数量
@property(nonatomic, readwrite) uint32_t sendMaxNum;

/// 创建公司id
@property(nonatomic, readwrite) uint64_t companyId;

/// 创建公司
@property(nonatomic, readwrite, copy, null_resettable) NSString *companyName;

@property(nonatomic, readwrite) uint64_t createStaffId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createStaffName;

@property(nonatomic, readwrite) uint64_t createTime;

@end

#pragma mark - UserCoupon

typedef GPB_ENUM(UserCoupon_FieldNumber) {
  UserCoupon_FieldNumber_Id_p = 1,
  UserCoupon_FieldNumber_TemplateId = 2,
  UserCoupon_FieldNumber_UserId = 3,
  UserCoupon_FieldNumber_StartDate = 4,
  UserCoupon_FieldNumber_EndDate = 5,
  UserCoupon_FieldNumber_CreateTime = 6,
  UserCoupon_FieldNumber_UseTime = 7,
  UserCoupon_FieldNumber_SendCompanyId = 8,
  UserCoupon_FieldNumber_SendStaffId = 9,
  UserCoupon_FieldNumber_UseOrgId = 10,
  UserCoupon_FieldNumber_UseBranchId = 11,
  UserCoupon_FieldNumber_Status = 12,
  UserCoupon_FieldNumber_ChannelId = 13,
};

/// 用户优惠券
@interface UserCoupon : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 模板ID
@property(nonatomic, readwrite) uint64_t templateId;

/// 用户ID
@property(nonatomic, readwrite) uint64_t userId;

/// 开始日期
@property(nonatomic, readwrite, copy, null_resettable) NSString *startDate;

/// 结束日期
@property(nonatomic, readwrite, copy, null_resettable) NSString *endDate;

/// 发放时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 使用时间
@property(nonatomic, readwrite) uint64_t useTime;

/// 发放公司ID
@property(nonatomic, readwrite) uint64_t sendCompanyId;

/// 发放员工ID
@property(nonatomic, readwrite) uint64_t sendStaffId;

/// 使用机构ID
@property(nonatomic, readwrite) uint64_t useOrgId;

/// 使用科室ID
@property(nonatomic, readwrite) uint64_t useBranchId;

/// 状态 1-未使用 2-已使用
@property(nonatomic, readwrite) uint32_t status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@end

#pragma mark - UserJGModel

typedef GPB_ENUM(UserJGModel_FieldNumber) {
  UserJGModel_FieldNumber_JpushId = 1,
  UserJGModel_FieldNumber_JgAppId = 2,
  UserJGModel_FieldNumber_UserId = 3,
  UserJGModel_FieldNumber_HgId = 4,
  UserJGModel_FieldNumber_CreateTime = 5,
  UserJGModel_FieldNumber_DeviceType = 6,
  UserJGModel_FieldNumber_PushType = 7,
};

/// 极光用户表
@interface UserJGModel : GPBMessage

/// 极光推送设备ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *jpushId;

/// 1-用户端 2-企业端
@property(nonatomic, readwrite) uint32_t jgAppId;

/// 用户ID
@property(nonatomic, readwrite) uint64_t userId;

/// 护工ID
@property(nonatomic, readwrite) uint64_t hgId;

/// 登陆时间
@property(nonatomic, readwrite) uint64_t createTime;

/// 设备类型 1-安卓 2-IOS
@property(nonatomic, readwrite) uint32_t deviceType;

/// 0-极光 1-小米 2-华为
@property(nonatomic, readwrite) uint32_t pushType;

@end

#pragma mark - RechargeSetting

typedef GPB_ENUM(RechargeSetting_FieldNumber) {
  RechargeSetting_FieldNumber_Id_p = 1,
  RechargeSetting_FieldNumber_Name = 2,
  RechargeSetting_FieldNumber_Fee = 3,
  RechargeSetting_FieldNumber_Present = 4,
  RechargeSetting_FieldNumber_CreateTime = 5,
  RechargeSetting_FieldNumber_FeeStr = 6,
  RechargeSetting_FieldNumber_PresentStr = 7,
};

/// 充值配置
@interface RechargeSetting : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

/// 充值描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/// 充值金额
@property(nonatomic, readwrite) uint32_t fee;

/// 赠送金额
@property(nonatomic, readwrite) uint32_t present;

@property(nonatomic, readwrite) uint64_t createTime;

/// 充值金额
@property(nonatomic, readwrite, copy, null_resettable) NSString *feeStr;

/// 赠送金额
@property(nonatomic, readwrite, copy, null_resettable) NSString *presentStr;

@end

#pragma mark - FeedBack

typedef GPB_ENUM(FeedBack_FieldNumber) {
  FeedBack_FieldNumber_Id_p = 1,
  FeedBack_FieldNumber_UserId = 2,
  FeedBack_FieldNumber_Suggest = 3,
  FeedBack_FieldNumber_CreateChannel = 4,
  FeedBack_FieldNumber_CreateTime = 5,
  FeedBack_FieldNumber_Reply = 6,
  FeedBack_FieldNumber_State = 7,
  FeedBack_FieldNumber_ReplyStaffId = 8,
  FeedBack_FieldNumber_ReplyStaffName = 9,
  FeedBack_FieldNumber_FbType = 10,
  FeedBack_FieldNumber_UserName = 11,
  FeedBack_FieldNumber_Phone = 12,
  FeedBack_FieldNumber_ReplyTime = 13,
  FeedBack_FieldNumber_FeedbackType = 14,
  FeedBack_FieldNumber_OrgId = 15,
};

///意见反馈
@interface FeedBack : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite) uint64_t userId;

/// 意见内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *suggest;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createChannel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/// 客服回复
@property(nonatomic, readwrite, copy, null_resettable) NSString *reply;

/// 1 未回复 2已回复
@property(nonatomic, readwrite) uint32_t state;

/// 回复人id
@property(nonatomic, readwrite) uint64_t replyStaffId;

/// 回复人姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *replyStaffName;

/// 类型 1-用户端 2-企业端
@property(nonatomic, readwrite) uint32_t fbType;

/// 反馈人
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

/// 反馈人手机号
@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

/// 反馈时间
@property(nonatomic, readwrite, copy, null_resettable) NSString *replyTime;

/// 反馈类型 0-其他问题 1-住院陪护相关 2-提现相关 3-长护险相关
@property(nonatomic, readwrite) uint32_t feedbackType;

/// 机构ID
@property(nonatomic, readwrite) uint64_t orgId;

@end

#pragma mark - Language

typedef GPB_ENUM(Language_FieldNumber) {
  Language_FieldNumber_Id_p = 1,
  Language_FieldNumber_Name = 2,
};

/// 语种
@interface Language : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - Information

typedef GPB_ENUM(Information_FieldNumber) {
  Information_FieldNumber_Id_p = 1,
  Information_FieldNumber_ImgURL = 2,
  Information_FieldNumber_Title = 3,
  Information_FieldNumber_Sketch = 4,
  Information_FieldNumber_CreateTime = 5,
  Information_FieldNumber_Description_p = 6,
  Information_FieldNumber_Status = 7,
  Information_FieldNumber_URL = 8,
};

/// 健康资讯
@interface Information : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

/// 图片
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgURL;

/// 标题
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/// 简述
@property(nonatomic, readwrite, copy, null_resettable) NSString *sketch;

@property(nonatomic, readwrite) uint64_t createTime;

/// 详情
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/// 0-有效 -1-已删除
@property(nonatomic, readwrite) uint32_t status;

/// 跳转链接
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - HospitalBra

typedef GPB_ENUM(HospitalBra_FieldNumber) {
  HospitalBra_FieldNumber_Name = 1,
  HospitalBra_FieldNumber_Sex = 2,
  HospitalBra_FieldNumber_Age = 3,
  HospitalBra_FieldNumber_Phone = 4,
  HospitalBra_FieldNumber_BranchName = 5,
  HospitalBra_FieldNumber_OrgName = 6,
  HospitalBra_FieldNumber_OrgNo = 7,
  HospitalBra_FieldNumber_AdmissionDate = 8,
  HospitalBra_FieldNumber_OrgId = 9,
  HospitalBra_FieldNumber_BranchId = 10,
  HospitalBra_FieldNumber_KinsId = 11,
  HospitalBra_FieldNumber_ImgId = 12,
  HospitalBra_FieldNumber_BedNo = 13,
  HospitalBra_FieldNumber_InStatus = 14,
};

/// 入院通知单或住院手环识别对象
@interface HospitalBra : GPBMessage

/// 姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/// 性别 0-未知 1-男 2-女
@property(nonatomic, readwrite) uint32_t sex;

/// 年龄
@property(nonatomic, readwrite) uint32_t age;

/// 手机号
@property(nonatomic, readwrite, copy, null_resettable) NSString *phone;

/// 科室名
@property(nonatomic, readwrite, copy, null_resettable) NSString *branchName;

/// 机构名
@property(nonatomic, readwrite, copy, null_resettable) NSString *orgName;

/// 住院号
@property(nonatomic, readwrite, copy, null_resettable) NSString *orgNo;

/// 入院日期
@property(nonatomic, readwrite, copy, null_resettable) NSString *admissionDate;

/// 机构id
@property(nonatomic, readwrite) uint64_t orgId;

/// 科室id
@property(nonatomic, readwrite) uint64_t branchId;

/// 被陪护人id
@property(nonatomic, readwrite) uint64_t kinsId;

/// 识别图片的图片id
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgId;

/// 床号
@property(nonatomic, readwrite, copy, null_resettable) NSString *bedNo;

/// 是否可以下单 0-可以 1-不可以
@property(nonatomic, readwrite) uint32_t inStatus;

@end

#pragma mark - WxKeywordReply

typedef GPB_ENUM(WxKeywordReply_FieldNumber) {
  WxKeywordReply_FieldNumber_ToUserName = 1,
  WxKeywordReply_FieldNumber_FromUserName = 2,
  WxKeywordReply_FieldNumber_CreateTime = 3,
  WxKeywordReply_FieldNumber_MsgType = 4,
  WxKeywordReply_FieldNumber_Content = 5,
  WxKeywordReply_FieldNumber_MsgId = 6,
};

/// 微信关键字回复(字段为官方)
@interface WxKeywordReply : GPBMessage

/// 	接收方帐号（收到的OpenID）
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUserName;

///	开发者微信号
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUserName;

///	消息创建时间 （整型）
@property(nonatomic, readwrite) uint64_t createTime;

///  消息类型 text- 文本
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgType;

///  回复的消息内容（换行：在content中能够换行，微信客户端就支持换行显示）
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

///  消息id
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@end

#pragma mark - WorkbenchVO

typedef GPB_ENUM(WorkbenchVO_FieldNumber) {
  WorkbenchVO_FieldNumber_Num = 1,
  WorkbenchVO_FieldNumber_Desc = 2,
  WorkbenchVO_FieldNumber_NativeURL = 3,
};

/// 企业端工作台
@interface WorkbenchVO : GPBMessage

/// 数据
@property(nonatomic, readwrite, copy, null_resettable) NSString *num;

/// 数据简介
@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

/// 跳转url
@property(nonatomic, readwrite, copy, null_resettable) NSString *nativeURL;

@end

#pragma mark - CommonToolsVO

typedef GPB_ENUM(CommonToolsVO_FieldNumber) {
  CommonToolsVO_FieldNumber_IconURL = 1,
  CommonToolsVO_FieldNumber_Desc = 2,
  CommonToolsVO_FieldNumber_NativeURL = 3,
};

/// 企业端常用工具
@interface CommonToolsVO : GPBMessage

/// 图片地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *iconURL;

/// 工具描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

/// 跳转地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *nativeURL;

@end

#pragma mark - MyScheduleVO

typedef GPB_ENUM(MyScheduleVO_FieldNumber) {
  MyScheduleVO_FieldNumber_OrderId = 1,
  MyScheduleVO_FieldNumber_InsureNo = 2,
  MyScheduleVO_FieldNumber_ServiceItem = 3,
  MyScheduleVO_FieldNumber_ServiceType = 4,
  MyScheduleVO_FieldNumber_KinsName = 5,
  MyScheduleVO_FieldNumber_Condition = 6,
  MyScheduleVO_FieldNumber_ConditionStr = 7,
  MyScheduleVO_FieldNumber_DayNum = 8,
  MyScheduleVO_FieldNumber_AddrDetail = 9,
  MyScheduleVO_FieldNumber_ContactPhone = 10,
  MyScheduleVO_FieldNumber_StartDate = 11,
};

/// 我的日程
@interface MyScheduleVO : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

/// 申请单号
@property(nonatomic, readwrite, copy, null_resettable) NSString *insureNo;

/// 服务项
@property(nonatomic, readwrite, copy, null_resettable) NSString *serviceItem;

/// 服务类型
@property(nonatomic, readwrite) uint32_t serviceType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *kinsName;

@property(nonatomic, readwrite) uint32_t condition;

/// 状态描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *conditionStr;

/// 离服务到期还N天，或距上次更新已N天
@property(nonatomic, readwrite) uint32_t dayNum;

/// 服务地点或联系地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *addrDetail;

/// 联系电话
@property(nonatomic, readwrite, copy, null_resettable) NSString *contactPhone;

/// 预约开始时间
@property(nonatomic, readwrite, copy, null_resettable) NSString *startDate;

@end

#pragma mark - BalanceData

typedef GPB_ENUM(BalanceData_FieldNumber) {
  BalanceData_FieldNumber_Id_p = 1,
  BalanceData_FieldNumber_CompanyId = 2,
  BalanceData_FieldNumber_OrgId = 3,
  BalanceData_FieldNumber_OrderId = 6,
  BalanceData_FieldNumber_InvoiceNo = 7,
  BalanceData_FieldNumber_TransType = 8,
  BalanceData_FieldNumber_PaykindCode = 9,
  BalanceData_FieldNumber_TotCost = 10,
  BalanceData_FieldNumber_OwnCost = 11,
  BalanceData_FieldNumber_BeginDate = 12,
  BalanceData_FieldNumber_EndDate = 13,
  BalanceData_FieldNumber_BalanceType = 14,
  BalanceData_FieldNumber_BalanceOpercode = 15,
  BalanceData_FieldNumber_WasteOpercode = 16,
  BalanceData_FieldNumber_WasteDate = 17,
  BalanceData_FieldNumber_CreateTime = 18,
};

/// 中肿his结算数据
@interface BalanceData : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

@property(nonatomic, readwrite) uint64_t companyId;

@property(nonatomic, readwrite) uint64_t orgId;

/// 订单id
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

/// 操作记录id
@property(nonatomic, readwrite, copy, null_resettable) NSString *invoiceNo;

/// 交易类型 1-正交易 2-反交易
@property(nonatomic, readwrite) uint32_t transType;

/// 结算类别 01–自费
@property(nonatomic, readwrite, copy, null_resettable) NSString *paykindCode;

/// 总金额
@property(nonatomic, readwrite, copy, null_resettable) NSString *totCost;

/// 自费金额
@property(nonatomic, readwrite, copy, null_resettable) NSString *ownCost;

/// 起始日期
@property(nonatomic, readwrite) uint64_t beginDate;

/// 终止日期
@property(nonatomic, readwrite) uint64_t endDate;

/// 结算类型 0-出院结算
@property(nonatomic, readwrite, copy, null_resettable) NSString *balanceType;

/// 结算操作员
@property(nonatomic, readwrite, copy, null_resettable) NSString *balanceOpercode;

/// 作废操作人
@property(nonatomic, readwrite, copy, null_resettable) NSString *wasteOpercode;

/// 作废时间
@property(nonatomic, readwrite, copy, null_resettable) NSString *wasteDate;

@property(nonatomic, readwrite) uint64_t createTime;

@end

#pragma mark - UserSituation

typedef GPB_ENUM(UserSituation_FieldNumber) {
  UserSituation_FieldNumber_Id_p = 1,
  UserSituation_FieldNumber_PatientName = 2,
  UserSituation_FieldNumber_Status = 3,
  UserSituation_FieldNumber_OrgNo = 4,
  UserSituation_FieldNumber_DeptName = 5,
  UserSituation_FieldNumber_DeptId = 6,
  UserSituation_FieldNumber_BedNo = 7,
  UserSituation_FieldNumber_AdmissionTime = 8,
  UserSituation_FieldNumber_AdmissionTimeStr = 9,
  UserSituation_FieldNumber_PatientInfo = 10,
  UserSituation_FieldNumber_CreateTime = 11,
  UserSituation_FieldNumber_OrderStatus = 12,
  UserSituation_FieldNumber_OrgNumber = 13,
  UserSituation_FieldNumber_ToDeptName = 14,
  UserSituation_FieldNumber_NewbedNo = 15,
};

/// 中肿his入院出院信息
@interface UserSituation : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *patientName;

/// 状态 	1-入院2-出院 3-转科
@property(nonatomic, readwrite) uint32_t status;

/// 住院号	
@property(nonatomic, readwrite, copy, null_resettable) NSString *orgNo;

/// 科室名	
@property(nonatomic, readwrite, copy, null_resettable) NSString *deptName;

/// 科室Id
@property(nonatomic, readwrite) uint64_t deptId;

/// 床号	
@property(nonatomic, readwrite, copy, null_resettable) NSString *bedNo;

@property(nonatomic, readwrite) uint64_t admissionTime;

/// 出院时间\\入院时间	格式：yyyy-MM-dd HH:mm:ss
@property(nonatomic, readwrite, copy, null_resettable) NSString *admissionTimeStr;

/// 入院诊断
@property(nonatomic, readwrite, copy, null_resettable) NSString *patientInfo;

@property(nonatomic, readwrite) uint64_t createTime;

/// 下单状态  1-未下单2-已下单 3-已出院 或 转科状态 1-未转科 2-已转科
@property(nonatomic, readwrite) uint32_t orderStatus;

/// 住院流水号
@property(nonatomic, readwrite, copy, null_resettable) NSString *orgNumber;

/// 转科时转入的科室
@property(nonatomic, readwrite, copy, null_resettable) NSString *toDeptName;

/// 转科时转入的床号
@property(nonatomic, readwrite, copy, null_resettable) NSString *newbedNo;

@end

#pragma mark - BigStatistics

typedef GPB_ENUM(BigStatistics_FieldNumber) {
  BigStatistics_FieldNumber_Id_p = 1,
  BigStatistics_FieldNumber_OrderNumber = 2,
  BigStatistics_FieldNumber_ServiceHistogram = 3,
  BigStatistics_FieldNumber_OnLineOrg = 4,
  BigStatistics_FieldNumber_ServiceType = 5,
  BigStatistics_FieldNumber_HgList = 6,
  BigStatistics_FieldNumber_FeedbackHistogram = 7,
  BigStatistics_FieldNumber_FeedbackList = 8,
  BigStatistics_FieldNumber_UpdateTime = 9,
  BigStatistics_FieldNumber_CreateTime = 10,
  BigStatistics_FieldNumber_CompanyId = 11,
};

/// 大屏数据统计 
@interface BigStatistics : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 订单数量
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNumber;

/// 柱状图-服务类型次数
@property(nonatomic, readwrite, copy, null_resettable) NSString *serviceHistogram;

/// 上线机构-arr
@property(nonatomic, readwrite, copy, null_resettable) NSString *onLineOrg;

/// 服务类型占比
@property(nonatomic, readwrite, copy, null_resettable) NSString *serviceType;

/// 明星护工集合
@property(nonatomic, readwrite, copy, null_resettable) NSString *hgList;

/// 柱状图-意见评价
@property(nonatomic, readwrite, copy, null_resettable) NSString *feedbackHistogram;

/// 意见评价列表
@property(nonatomic, readwrite, copy, null_resettable) NSString *feedbackList;

/// 修改订单
@property(nonatomic, readwrite, copy, null_resettable) NSString *updateTime;

/// 创建时间
@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/// 公司id
@property(nonatomic, readwrite) uint64_t companyId;

@end

#pragma mark - AdModel

typedef GPB_ENUM(AdModel_FieldNumber) {
  AdModel_FieldNumber_Id_p = 1,
  AdModel_FieldNumber_ImgId = 2,
  AdModel_FieldNumber_URL = 3,
  AdModel_FieldNumber_AdType = 4,
  AdModel_FieldNumber_Status = 5,
  AdModel_FieldNumber_UpdateStaffId = 7,
  AdModel_FieldNumber_UpdateStaffName = 8,
  AdModel_FieldNumber_UpdateTime = 9,
  AdModel_FieldNumber_CreateTime = 10,
  AdModel_FieldNumber_ImgURL = 11,
};

@interface AdModel : GPBMessage

@property(nonatomic, readwrite) uint64_t id_p;

/// 图片id
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgId;

/// 跳转链接
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/// 广告位置类型 0-订单详情页 -1-支付成功页
@property(nonatomic, readwrite) uint32_t adType;

/// 0-有效 -1-已删除
@property(nonatomic, readwrite) uint32_t status;

/// 最后修改员工ID
@property(nonatomic, readwrite) uint64_t updateStaffId;

/// 最后修改员工名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *updateStaffName;

/// 最后修改时间
@property(nonatomic, readwrite) uint64_t updateTime;

/// 创建时间
@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/// 图片url
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgURL;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
