// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CMD.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum APP_COMMAND

typedef GPB_ENUM(APP_COMMAND) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  APP_COMMAND_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APP_COMMAND_Default = 0,

  ///测试web应用是否存活
  APP_COMMAND_Ping = 1,

  ///更新闪屏
  APP_COMMAND_GetSplash = 2,

  ///跟新配置信息
  APP_COMMAND_GetSetting = 3,

  ///统计上报
  APP_COMMAND_StatReport = 4,

  ///获取短信验证码
  APP_COMMAND_GetSmscode = 5,

  ///验证手机号
  APP_COMMAND_VerifyPhone = 6,

  ///登录
  APP_COMMAND_Login = 7,

  ///护工登录
  APP_COMMAND_SaasLogin = 8,

  ///App版本检测
  APP_COMMAND_AppVersionCheck = 9,

  ///获取融云Token
  APP_COMMAND_GetRongToken = 11,

  ///识别身份证号码并返回给客户端
  APP_COMMAND_IdcardRecognize = 20,

  ///APP退出登录
  APP_COMMAND_Applogout = 21,

  /// 获取充值项
  APP_COMMAND_GetRechargeSetting = 30,

  /// 预支付
  APP_COMMAND_DoPay = 31,

  /// 再次确认支付成功
  APP_COMMAND_GetDoPay = 32,

  /// 获取二维码URL
  APP_COMMAND_GetQrcode = 33,

  /// 住院手环识别和入院通知书识别
  APP_COMMAND_OrgNorecognize = 34,

  /// 获取当前系统支持的支付方式
  APP_COMMAND_GetPayType = 35,

  /// 校正二维码支付状态
  APP_COMMAND_RectifyPayQrc = 36,

  /// 记录服务器错误信息
  APP_COMMAND_CreateError = 37,

  /// 记录页面打开耗时
  APP_COMMAND_CreateWebpageTime = 38,

  /// 根据自照护工手机号查询身份证号
  APP_COMMAND_GetHgidcardByPhone = 39,

  /// 查询第三方支付结果c
  APP_COMMAND_CheckPayStatus = 40,

  /// 重置支付标示
  APP_COMMAND_ResetPayFlag = 41,

  /// 剪切图片
  APP_COMMAND_CutImage = 42,

  /// 中肿审核陪人床接口
  APP_COMMAND_CheckPrczz = 1000,

  ///---------用户h5接口列表
  APP_COMMAND_GetSettings = 3000,

  /// H5开户申请
  APP_COMMAND_SaveCompany = 3001,

  /// 上传微信图片
  APP_COMMAND_GetImageToWx = 3002,

  /// 获取附近或本市内的医院列表
  APP_COMMAND_GetOrgList = 3003,

  /// 获取医院和科室的接口
  APP_COMMAND_GetOrgAndBranch = 3004,

  /// 通过科室获取定价
  APP_COMMAND_GetPrice = 3005,

  /// 通过科室获取房间和床位
  APP_COMMAND_GetRoomAndBed = 3006,

  /// 保存订单的评价
  APP_COMMAND_SaveOrderPraise = 3007,

  /// H5删除系统消息
  APP_COMMAND_DeleteSystemMsg = 3008,

  /// 获取用户账户信息
  APP_COMMAND_GetUserAccount = 3009,

  /// 获取用户信息
  APP_COMMAND_GetUserInfo = 3010,

  /// 获取系统消息列表
  APP_COMMAND_GetUserSystemMessage = 3011,

  /// 标记消息为已读
  APP_COMMAND_MarkSystemMsgAsRead = 3012,

  /// 获取订单时间范围
  APP_COMMAND_GetOrderTime = 3013,

  /// 添加亲属信息
  APP_COMMAND_AddKinsfolk = 3014,

  /// 修改亲属信息
  APP_COMMAND_UpdateKinsfolk = 3015,

  /// 回显亲属信息
  APP_COMMAND_GetKinsfolk = 3016,

  /// 添加用户地址
  APP_COMMAND_AddUserAddress = 3017,

  /// 修改用户地址
  APP_COMMAND_UpdateUserAddress = 3018,

  /// 回显用户地址
  APP_COMMAND_GetUserAddress = 3019,

  /// 获取亲属列表
  APP_COMMAND_ListKinsfolk = 3020,

  /// 获取用户地址列表
  APP_COMMAND_ListUserAddress = 3021,

  /// 设置用户默认地址
  APP_COMMAND_SetDefaultAddress = 3022,

  /// 添加反馈信息
  APP_COMMAND_AddFeedBack = 3023,

  /// 删除亲属
  APP_COMMAND_DelKinsfolk = 3024,

  /// 删除用户地址
  APP_COMMAND_DelUserAddress = 3025,

  /// 设置默认亲属
  APP_COMMAND_SetDefaultKinsfolk = 3026,

  /// 修改个人信息
  APP_COMMAND_UpdateUserInfo = 3027,

  /// 通过住院号获取用户信息
  APP_COMMAND_GetUserInfoByOrgNo = 3028,

  /// 获取反馈列表
  APP_COMMAND_GetFeedBackList = 3029,

  /// 获取反馈
  APP_COMMAND_GetFeedBack = 3030,

  /// 获取机构详情
  APP_COMMAND_GetOrg = 3031,

  /// 获取首页数据（需登录）
  APP_COMMAND_Index = 3035,

  /// 获取微信配置
  APP_COMMAND_GetWxOauth = 3036,

  /// 银生宝支付通知结果
  APP_COMMAND_NotifyYsbpay = 3037,

  /// H5创建订单
  APP_COMMAND_CreateOrder = 3040,

  /// H5获取订单列表
  APP_COMMAND_GetOrderList = 3041,

  /// H5预交金支付详情页
  APP_COMMAND_GetPayDetail = 3042,

  /// H5获取订单项列表
  APP_COMMAND_ListOrderItem = 3043,

  /// H5获取结算列表
  APP_COMMAND_ListSettlement = 3044,

  /// 重下此单,订单信息回显
  APP_COMMAND_ReOrder = 3046,

  /// 取消订单
  APP_COMMAND_CancelOrder = 3047,

  /// 支付预交金详情页
  APP_COMMAND_PrePayAmountDetail = 3048,

  /// 中途支付详情页
  APP_COMMAND_SettlPayDetail = 3049,

  /// 订单结算详情页
  APP_COMMAND_OrderPayDetail = 3050,

  /// 获取订单详情
  APP_COMMAND_GetOrderDetail = 3051,

  /// 附加服务调整明细
  APP_COMMAND_GetOrderItemInvertList = 3052,

  /// 确认订单完成
  APP_COMMAND_ConfirmOrderFinish = 3053,

  /// 二维码订单详情页
  APP_COMMAND_GetOrderDetailQrc = 3054,

  /// 中途支付详情页(二维码)
  APP_COMMAND_SettlPayDetailQrc = 3055,

  /// 订单签名
  APP_COMMAND_UpdateOrderSignPic = 3056,

  /// 获取订单是否重复下单
  APP_COMMAND_GetOrderRepetition = 3057,

  /// 获取订单住院号有多少待结算
  APP_COMMAND_GetOrgNoorderList = 3058,

  /// 获取创建陪人床订单基础信息
  APP_COMMAND_GetCreateOrderPrcInfo = 3059,

  /// 批量结算订单
  APP_COMMAND_BatchSettleOrder = 3060,

  /// 创建陪人床订单
  APP_COMMAND_CreateOrderPrc = 3061,

  /// 微信支付失败取消订单
  APP_COMMAND_UpdateOrderPrcPayStatus = 3062,

  /// 确认订单批量完成
  APP_COMMAND_ConfirmOrderBatchFinish = 3063,

  /// 申请长护险
  APP_COMMAND_AddInsure = 3100,

  /// 获取长护险详情
  APP_COMMAND_GetInsureDetail = 3101,

  /// 获取长护险列表
  APP_COMMAND_GetInsureList = 3102,

  /// 新增用户自评
  APP_COMMAND_AddInsureAssess = 3103,

  /// 获取用户自评
  APP_COMMAND_GetInsureAssess = 3104,

  /// 校验长护险参数
  APP_COMMAND_CheckInsureParam = 3105,

  /// 获取复审报告
  APP_COMMAND_GetInsureAgainAssess = 3106,

  /// 获取长护险资格人列表
  APP_COMMAND_GetInsureAccount = 3107,

  /// 获取长护险补贴明细
  APP_COMMAND_GetInsureAccountDetail = 3108,

  /// 强制提交长护险
  APP_COMMAND_ForceSubmitInsure = 3109,

  /// 获取健康经理长护险业绩
  APP_COMMAND_GetInsurePerformanceInfo = 3110,

  /// 获取用户消息类型列表
  APP_COMMAND_GetMsgList = 3150,

  /// 获取用户某种类型的消息列表
  APP_COMMAND_GetUserMsgByType = 3151,

  /// 检查h5登陆状态
  APP_COMMAND_CheckLogin = 3180,

  /// 验证h5切换登陆验证码
  APP_COMMAND_VerifySmscode = 3181,

  /// 提现
  APP_COMMAND_Withdraw = 3190,

  /// 自照护理员申请
  APP_COMMAND_AddInsureStaffApply = 3200,

  /// 获取自照护理员申请列表
  APP_COMMAND_GetApplyList = 3201,

  /// 获取自照护理员申请详情
  APP_COMMAND_GetApplyDetail = 3202,

  /// 获取用户银行卡列表
  APP_COMMAND_ListUserBank = 3220,

  /// 修改用户银行卡
  APP_COMMAND_UpdateUserBank = 3221,

  /// 新增用户银行卡
  APP_COMMAND_AddUserBank = 3222,

  /// 删除银行卡（逻辑删除）
  APP_COMMAND_DelUserBank = 3223,

  /// 扫码验证是否可支付
  APP_COMMAND_ScanPay = 3300,

  /// 获取广告位信息
  APP_COMMAND_GetAd = 3310,

  /// 充值预付款
  APP_COMMAND_RechargePrepayFee = 3350,

  /// 获取长护险服务定价
  APP_COMMAND_GetInsurePriceList = 3355,

  /// 获取长护险下单信息
  APP_COMMAND_GetInsureOrderInfo = 3356,

  /// 长护险下单
  APP_COMMAND_AddInsureOrder = 3357,

  /// 获取服务定价详情
  APP_COMMAND_GetPriceById = 3358,

  /// 获取订单列表（新）
  APP_COMMAND_GetOrderListNew = 3359,

  /// 获取居家订单详情
  APP_COMMAND_GetHomeOrderDetail = 3360,

  /// 取消订单
  APP_COMMAND_CancelOrderNew = 3361,

  /// 获取护工或护士信息
  APP_COMMAND_GetHginfoByOrder = 3362,

  /// 获取照护计划详情
  APP_COMMAND_GetOrderTendDetail = 3363,

  /// 照护计划列表
  APP_COMMAND_GetOrderTendList = 3364,

  /// 获取补贴估算
  APP_COMMAND_GetReckonSubsidy = 3365,

  /// 获取订单每日明细列表
  APP_COMMAND_GetInsureOrderTendItem = 3366,

  /// 获取每日明细详情
  APP_COMMAND_GetInsureOrderTendItemDetail = 3367,

  /// 获取回访反显
  APP_COMMAND_GetInsureOrderVisitDetail = 3368,

  /// 回访记录列表
  APP_COMMAND_GetInsureOrderVisitList = 3369,

  /// 获取回访记录生命体征信息
  APP_COMMAND_GetInsureOrderVisitVita = 3370,

  /// 获取回访记录质控内容信息
  APP_COMMAND_GetInsureOrderVisitQuality = 3371,

  /// 获取带教记录
  APP_COMMAND_GetTeachRecord = 3372,

  /// 获取带教记录列表
  APP_COMMAND_GetInusreOrderTeachRecord = 3373,

  /// 获取代付订单列表
  APP_COMMAND_GetOrderListReplacePay = 3374,

  /// 订单结算前校验当前是否需要合并结算
  APP_COMMAND_CheckOrderSettle = 3375,

  /// 获取好大夫链接
  APP_COMMAND_GetGoodDoctorURL = 3390,

  /// 根据订单获取机构
  APP_COMMAND_GetFeedBackOrderOrg = 3400,

  ///---------用户app接口列表
  APP_COMMAND_AppgetOrgList = 5000,

  /// 获取闪屏
  APP_COMMAND_AppgetSplashScreen = 5001,

  /// 获取用户信息
  APP_COMMAND_AppgetUserInfo = 5002,

  /// 更新用户消息
  APP_COMMAND_AppupdateUserInfo = 5003,

  /// 获取首页icon和链接
  APP_COMMAND_AppgetSettings = 5005,

  /// 获取机构和科室列表
  APP_COMMAND_AppgetOrgAndBranch = 5007,

  /// 获取房间和床位
  APP_COMMAND_AppgetRoomAndBed = 5008,

  /// 获取套餐列表
  APP_COMMAND_AppgetPrice = 5009,

  ///添加用户地址
  APP_COMMAND_AppaddUserAddress = 5010,

  ///修改用户地址
  APP_COMMAND_AppupdateUserAddress = 5011,

  ///删除用户地址
  APP_COMMAND_AppdelUserAddress = 5012,

  ///获取用户地址列表
  APP_COMMAND_ApplistUserAddress = 5013,

  ///设置用户默认地址
  APP_COMMAND_AppsetDefaultAddress = 5014,

  ///添加亲属
  APP_COMMAND_AppaddKinsfolk = 5020,

  ///删除亲属
  APP_COMMAND_AppdelKinsfolk = 5021,

  ///修改亲属
  APP_COMMAND_AppupdateKinsfolk = 5022,

  ///亲属列表
  APP_COMMAND_ApplistKinsfolk = 5023,

  ///意见反馈
  APP_COMMAND_AppaddFeedBack = 5030,

  /// 保存评价
  APP_COMMAND_AppsaveOrderPraise = 5031,

  /// 查看订单的评价
  APP_COMMAND_AppgetOrderPraise = 5032,

  /// 创建订单
  APP_COMMAND_AppcreateOrder = 5033,

  /// 获取订单列表
  APP_COMMAND_AppgetOrderList = 5034,

  /// 获取支付详情
  APP_COMMAND_AppgetPayDetail = 5035,

  /// 重新下单
  APP_COMMAND_AppreOrder = 5036,

  /// 结算清单列表
  APP_COMMAND_ApplistSettlement = 5037,

  /// 每日明细列表
  APP_COMMAND_ApplistOrderItem = 5038,

  /// 预交金支付详情页
  APP_COMMAND_AppprePayAmountDetail = 5039,

  /// 取消订单
  APP_COMMAND_AppcancelOrder = 5040,

  /// 支付订单详情页
  APP_COMMAND_AppsettlPayDetail = 5041,

  /// 结算订单详情页
  APP_COMMAND_ApporderPayDetail = 5042,

  /// 获取首页内容（需登录）
  APP_COMMAND_Appindex = 5049,

  /// 获取时间段信息
  APP_COMMAND_AppgetOrderTime = 5050,

  /// 查看订单的评价
  APP_COMMAND_GetOrderPraise = 5051,

  /// 附加服务调整明细
  APP_COMMAND_AppgetOrderItemInvertList = 5052,

  /// 提现
  APP_COMMAND_Appwithdraw = 5100,

  /// 删除系统消息
  APP_COMMAND_AppdeleteSystemMessage = 5101,

  /// 获取钱包余额
  APP_COMMAND_AppgetUserAccount = 5102,

  ///设置默认亲属
  APP_COMMAND_AppsetDefaultKinsfolk = 5103,

  /// 获取亲属详情
  APP_COMMAND_AppgetKins = 5104,

  /// 获取订单是否重复下单
  APP_COMMAND_AppgetOrderRepetition = 5105,

  /// 获取订单详情
  APP_COMMAND_AppgetOrderDetail = 5200,

  /// 确认订单完成
  APP_COMMAND_AppconfirmOrderFinish = 5201,

  /// 申请长护险
  APP_COMMAND_AppaddInsure = 5230,

  /// 获取长护险申请详情
  APP_COMMAND_AppgetInsureDetail = 5231,

  /// 获取长护险列表
  APP_COMMAND_AppgetInsureList = 5232,

  /// 校验长护险参数
  APP_COMMAND_AppcheckInsureParam = 5233,

  /// 获取长护险补贴明细
  APP_COMMAND_AppgetInsureAccountDetail = 5234,

  /// 获取长护险资格人列表
  APP_COMMAND_AppgetInsureAccount = 5235,

  /// 强制提交申请长护险
  APP_COMMAND_AppforceSubmitInsure = 5236,

  /// 获取用户消息类型列表
  APP_COMMAND_AppgetMsgList = 5250,

  /// 获取用户某种消息列表（并标示已读）
  APP_COMMAND_AppGetUserMsgByType = 5251,

  /// 获取用户银行卡列表
  APP_COMMAND_ApplistUserBank = 5270,

  /// 新增用户银行卡
  APP_COMMAND_AppaddUserBank = 5271,

  /// 修改用银行卡
  APP_COMMAND_AppupdateUserBank = 5272,

  /// 删除银行卡（逻辑删除）
  APP_COMMAND_AppdelUserBank = 5273,

  /// 通过住院号获取用户信息
  APP_COMMAND_AppgetUserInfoByOrgNo = 5280,

  /// 获取长护险服务定价
  APP_COMMAND_AppgetInsurePriceList = 5290,

  /// 获取长护险下单信息
  APP_COMMAND_AppgetInsureOrderInfo = 5291,

  /// 长护险下单
  APP_COMMAND_AppaddInsureOrder = 5292,

  /// 获取订单列表（新）
  APP_COMMAND_AppgetOrderListNew = 5293,

  /// 获取居家长护险订单详情
  APP_COMMAND_AppgetHomeOrderDetail = 5294,

  /// 取消订单
  APP_COMMAND_AppcancelOrderNew = 5295,

  /// 获取护工或护士信息
  APP_COMMAND_AppgetHginfoByOrder = 5296,

  /// 照护计划详情
  APP_COMMAND_AppgetOrderTendDetail = 5297,

  /// 照护计划列表
  APP_COMMAND_AppgetOrderTendList = 5298,

  /// 获取补贴估算
  APP_COMMAND_AppgetReckonSubsidy = 5299,

  /// 获取订单每日明细列表
  APP_COMMAND_AppgetInsureOrderTendItem = 5300,

  /// 获取每日明细详情
  APP_COMMAND_AppgetInsureOrderTendItemDetail = 5301,

  /// 获取回访反显
  APP_COMMAND_AppgetInsureOrderVisitDetail = 5302,

  /// 回访记录列表
  APP_COMMAND_AppgetInsureOrderVisitList = 5303,

  /// 获取带教记录详情
  APP_COMMAND_AppgetTeachRecord = 5304,

  /// 获取带教记录列表
  APP_COMMAND_AppgetInusreOrderTeachRecord = 5305,

  ///---------企业app接口列表
  APP_COMMAND_SaasappgetBannerList = 7000,
  APP_COMMAND_SaasappgetSplashScreen = 7001,

  /// SAAS扫码登录获取二维码
  APP_COMMAND_SaasappgetLoginQrcode = 7010,

  /// SAAS扫码登录
  APP_COMMAND_SaasappscanLogin = 7011,

  /// SAAS获取用户kins信息
  APP_COMMAND_SaasappgetUserKins = 7012,

  /// SAAS注册用户信息
  APP_COMMAND_SaasappsignUserInfo = 7013,

  /// SAAS添加亲属关系
  APP_COMMAND_SaasappaddKinsfolk = 7014,

  /// 获取被陪护人信息
  APP_COMMAND_SaasappgetKins = 7015,

  /// 获取亲属列表
  APP_COMMAND_SaasappgetUserKinsList = 7016,

  /// 获取地址列表
  APP_COMMAND_SaasappgetUserAddrList = 7017,

  /// 判断该手机号是否存在
  APP_COMMAND_SaasappcheckUserExist = 7018,

  /// 获取企业端配置
  APP_COMMAND_SaasappgetSettings = 7019,

  /// 添加用户地址
  APP_COMMAND_SaasappaddUserAddr = 7020,

  /// 删除用户亲属信息
  APP_COMMAND_SaasappdelKinsfolk = 7021,

  /// 删除用户地址信息
  APP_COMMAND_SaasappdelUserAddress = 7022,

  /// 更新用户亲属信息
  APP_COMMAND_SaasappupdateKinsfolk = 7023,

  /// 更新用户地址信息
  APP_COMMAND_SaasappupdateUserAddress = 7024,

  /// 生成异号用户
  APP_COMMAND_SaasappcreateDiffnoUser = 7025,

  /// 获取工作台信息
  APP_COMMAND_SaasappgetMyWorkbench = 7026,

  /// 获取我的日程
  APP_COMMAND_SaasappgetSchedule = 7027,

  /// 通过住院号获取用户信息
  APP_COMMAND_SaasappgetUserInfoByOrgNo = 7028,

  /// 获取日程表信息
  APP_COMMAND_SaasappgetScheduleList = 7030,

  /// 获取护士评估列表
  APP_COMMAND_SaasappgetAssessList = 7080,

  /// 护士mmse评估
  APP_COMMAND_SaasappinsureAssessMmse = 7081,

  /// 护士添加病例
  APP_COMMAND_SaasappinsureAssessMedical = 7083,

  /// 获取adl评分
  APP_COMMAND_SaasappgetInsureAssessAdl = 7084,

  /// 获取mmse评分
  APP_COMMAND_SaasappgetInsureAssessMmse = 7085,

  /// 获取评估信息
  APP_COMMAND_SaasappgetInsureAssess = 7086,

  /// 更新订单信息
  APP_COMMAND_SaasappsaveInsureAssess = 7087,

  /// 长护险护士初审
  APP_COMMAND_SaasappinsureAssessFirst = 7088,

  /// 获取病例列表
  APP_COMMAND_SaasappgetInsureMedicalList = 7089,

  /// 修改申请单预约上门下单时间和设置暂不下单
  APP_COMMAND_SaasappupdateInsureOrder = 7090,

  /// 获取长护险补贴明细
  APP_COMMAND_SaasappgetInsureAccountDetail = 7091,

  /// 长护险申请
  APP_COMMAND_SaasappaddInsure = 7092,

  /// 长护险列表
  APP_COMMAND_SaasappgetInsureList = 7093,

  /// 长护险详情
  APP_COMMAND_SaasappgetInsureDetail = 7094,

  /// 操作长护险审核
  APP_COMMAND_SaasappinsureAssess = 7095,

  /// 长护险申请单添加数据及修改
  APP_COMMAND_SaasappsaveOrUpdateInsure = 7096,

  /// 获取订单详情
  APP_COMMAND_SaasappgetOrderDetail = 7100,

  /// 获取订单列表
  APP_COMMAND_SaasappgetOrderList = 7101,

  /// 获取订单详情
  APP_COMMAND_SaasappgetOrderInfo = 7102,

  /// 开启服务
  APP_COMMAND_SaasappsaveOrUpdateOrder = 7103,

  /// 新增订单
  APP_COMMAND_SaasappcreateOrder = 7104,

  /// 新增长护险order订单
  APP_COMMAND_SaasappcreateInsureOrder = 7105,

  /// 获取服务知情书
  APP_COMMAND_SaasappgetOrderInformed = 7106,

  /// 保存被陪护人order签名
  APP_COMMAND_SaasappupdateOrderSignPic = 7107,

  /// 添加订单医疗附加服务
  APP_COMMAND_SaasappaddOrderPrice = 7108,

  /// 订单信息推送
  APP_COMMAND_SaasapporderJpush = 7109,

  /// 获取订单每日明细
  APP_COMMAND_SaasapplistOrderItem = 7110,

  /// 护士、护工、督导、健康经理服务确认
  APP_COMMAND_SaasappconfirmOrderItem = 7111,

  /// 变更服务信息
  APP_COMMAND_SaasappupdateOrderServe = 7112,

  /// 变更记录
  APP_COMMAND_SaasappgetOrderProcessList = 7113,

  /// 取消关闭长护险订单项（指护工添加的长护险附加项）
  APP_COMMAND_SaasappcancelOrderItem = 7114,

  /// 订单支付详情页
  APP_COMMAND_SaasappsettlPayDetail = 7115,

  /// 变更信息反显
  APP_COMMAND_SaasappgetOrderService = 7116,

  /// 居家订单跳过评估
  APP_COMMAND_SaasappskipAssessOrder = 7118,

  /// 关闭订单
  APP_COMMAND_SaasappcancelOrder = 7119,

  /// 校验订单是否支付成功
  APP_COMMAND_SaasappcheckOrderPaied = 7120,

  /// 护工变更服务price接口--只针对于护工
  APP_COMMAND_SaasappupdateOrderServicePrice = 7121,

  /// 获取附加项列表（普通附加）及反显数据
  APP_COMMAND_SaasappgetOrderPriceInvert = 7122,

  /// 修改订单校正服务
  APP_COMMAND_SaasappaddOrderPriceItemRevise = 7123,

  /// 充值预付款
  APP_COMMAND_SaasapprechargePrepayFee = 7124,

  /// 待结算订单退款
  APP_COMMAND_SaasappconfirmOrderFinish = 7125,

  /// 订单已取消后退款
  APP_COMMAND_SaasapprefundOrder = 7126,

  /// 督导、护工开启关闭服务（新）（单纯关闭订单的改版。对应机构订单）
  APP_COMMAND_SaasappsaveOrUpdateOrderNew = 7127,

  /// 结束服务后订单服务项详情
  APP_COMMAND_SaasappgetOrderItemDetail = 7128,

  /// 修改订单明细
  APP_COMMAND_SaasappcreateOrUpdateOrderItemPrice = 7129,

  /// 获取计算订单优惠金额
  APP_COMMAND_SaasappgetOrderRebate = 7130,

  /// 修改订单优惠方式或者优惠金额
  APP_COMMAND_SaasappupdateOrderRebate = 7131,

  /// 订单今日陪人床反显
  APP_COMMAND_SaasappgetOrderItemDetailNowInvert = 7132,

  /// 获取订单夜陪服务信息
  APP_COMMAND_SaasappgetOrderItemNightList = 7133,

  /// 创建修改删除订单夜陪服务
  APP_COMMAND_SaasappsaveOrUpdateOrderItemNight = 7134,

  /// 转科室时确认新订单信息
  APP_COMMAND_SaasappconfirmNewOrder = 7135,

  /// 确认订单完成
  APP_COMMAND_SaasappconfirmOrderFinishNew = 7136,

  /// 获取订单接诊时间
  APP_COMMAND_SaasappgetOrderReceptionTime = 7137,

  /// 开启机构订单
  APP_COMMAND_SaasappstartOrgOrder = 7138,

  /// 更换订单护工（只针对于非承包制普陪订单）
  APP_COMMAND_SaasappupdateOrderHg = 7139,

  /// 忽略跳过签名
  APP_COMMAND_SaasappneglectOrderSignPic = 7140,

  /// 获取订单是否重复下单
  APP_COMMAND_SaasappgetOrderRepetition = 7141,

  /// 校验是否可以结束订单
  APP_COMMAND_SaasappcheckFinishOrder = 7142,

  /// 获取订单住院号有多少待结算
  APP_COMMAND_SaasappgetOrgNoorderList = 7143,

  /// 企业端获取订单陪人床签名列表
  APP_COMMAND_SaasappgetOrderPrcitemList = 7144,

  /// 获取机构与科室（废弃）
  APP_COMMAND_SaasappgetOrgAndBranch = 7150,

  /// 获取房间跟房间号
  APP_COMMAND_SaasappgetRoomAndBed = 7151,

  /// 获取服务
  APP_COMMAND_SaasappgetPrice = 7152,

  /// 获取服务信息
  APP_COMMAND_SaasappgetPriceList = 7153,

  /// 获取订单服务时间
  APP_COMMAND_SaasappgetOrderTime = 7154,

  /// 获取机构与科室（新，根据人员列表配置机构科室）
  APP_COMMAND_SaasappgetOrgAndBranchNew = 7155,

  /// 获取护士、护工、护士长、督导、健康经理信息
  APP_COMMAND_SaasappgetHgInfo = 7255,

  /// 修改护士、护工、护士长、督导、健康经理信息
  APP_COMMAND_SaasappupdateHgInfo = 7256,

  ///	SAASAPPGetSubserverList		= 7258;		// 获取护士长子订单列表
  APP_COMMAND_SaasappguideStaff = 7259,

  /// 获取我的护士、护工列表
  APP_COMMAND_SaasappgetHglist = 7260,

  /// 新 指派护工/护士/护士长/健康经理
  APP_COMMAND_SaasappguideStaffNew = 7261,

  /// 获取护工列表
  APP_COMMAND_SaasappgetStaffList = 7262,

  /// 切换督导的值班状态
  APP_COMMAND_SaasappupdateOnduty = 7263,

  /// 获取员工签名
  APP_COMMAND_SaasappgetHgSign = 7264,

  /// 新增修改员工签名信息
  APP_COMMAND_SaasappsaveOrUpdateHgSign = 7265,

  /// 标记消息已读
  APP_COMMAND_SaasappupdateMessageRead = 7300,

  /// 获取消息列表
  APP_COMMAND_SaasappgetMessageList = 7301,

  ///  获取某种分类消息的消息列表
  APP_COMMAND_SaasappgetMsgByType = 7302,

  /// 获取消息分类列表
  APP_COMMAND_SaasappgetMsgList = 7303,

  /// 提交护工意见反馈
  APP_COMMAND_SaasappaddFeedBack = 7310,

  /// 获取员工意见反馈列表
  APP_COMMAND_SaasappgetFeedBackList = 7311,

  /// 获取员工意见反馈详情
  APP_COMMAND_SaasappgetFeedBack = 7312,

  /// 扫码请求
  APP_COMMAND_Saasappscan = 7315,

  /// 轮询支付状态
  APP_COMMAND_SaasappcheckPayState = 7350,

  /// 长护险险订单被陪护人信息
  APP_COMMAND_SaasappgetKinsInsure = 7400,

  /// 获取自照家属信息
  APP_COMMAND_SaasappgetHgApply = 7401,

  /// 取消关闭长护险订单
  APP_COMMAND_SaasappcancelInsureOrder = 7402,

  /// 待接单状态接单并状态扭转到待派工
  APP_COMMAND_SaasappacceptInsureOrder = 7403,

  /// 获取长护险申请单复审通过列表
  APP_COMMAND_SaasappgetInsureRecheckList = 7404,

  /// 发放资质
  APP_COMMAND_SaasappgrantInsureOrder = 7405,

  /// 开启服务
  APP_COMMAND_SaasappopenInsureOrder = 7406,

  /// 变更陪护家属
  APP_COMMAND_SaasappsaveOrUpdateInsureOrderRelation = 7407,

  /// 结束订单
  APP_COMMAND_SaasappfinishInsureOrder = 7408,

  /// 订单结算前校验当前是否需要合并结算
  APP_COMMAND_SaasappcheckOrderSettle = 7409,

  /// 下长护险单
  APP_COMMAND_SaasappaddInsureOrder = 7410,

  /// 获取长护险服务定价
  APP_COMMAND_SaasappgetInsurePriceList = 7412,

  /// 获取长护险订单详情
  APP_COMMAND_SaasappgetInsureOrderDetail = 7413,

  /// 获取长护险下单信息
  APP_COMMAND_SaasappgetInsureOrderInfo = 7414,

  /// 获取订单列表
  APP_COMMAND_SaasappgetOrderListNew = 7415,

  /// 取消订单
  APP_COMMAND_SaasappcancelOrderNew = 7416,

  /// 下长护险带教订单
  APP_COMMAND_SaasappaddInsureOrderTeach = 7417,

  /// 获取长护险护士信息
  APP_COMMAND_SaasappgetInsureHginfo = 7430,

  /// 获取长护险护士列表
  APP_COMMAND_SaasappgetInsureHglist = 7431,

  /// 指派更换长护险订单护士
  APP_COMMAND_SaasappassignInsureHg = 7432,

  /// 获取护工或护士信息
  APP_COMMAND_SaasappgetHginfoByOrder = 7433,

  /// 长护险订单专用-指派人员
  APP_COMMAND_SaasappguideStaffInsureOrder = 7434,

  /// 获取护士/护工列表
  APP_COMMAND_SaasappgetHomeStaffList = 7435,

  /// 订单考核列表
  APP_COMMAND_SaasappgetInsureOrderCheckList = 7500,

  /// 创建订单考核
  APP_COMMAND_SaasappaddInsureOrderCheck = 7501,

  /// 照护计划详情
  APP_COMMAND_SaasappgetOrderTendDetail = 7550,

  /// 获取带教记录列表
  APP_COMMAND_SaasappgetInusreOrderTeachRecord = 7551,

  /// 添加带教记录
  APP_COMMAND_SaasappaddTeachRecord = 7552,

  /// 病症列表
  APP_COMMAND_SaasappgetIllnessList = 7600,

  /// 照护明细列表
  APP_COMMAND_SaasappgetTendDetailList = 7601,

  ///	SAASAPPAddInsureOrderTend	= 7650;	// 新增照护计划
  ///	SAASAPPUpdateInsureOrderTend= 7651;	// 修改照护方式
  APP_COMMAND_SaasappcheckInsureOrderTend = 7652,

  /// 护士长审核照护计划
  APP_COMMAND_SaasappgetOrderTendList = 7653,

  /// 保存照护计划明细
  APP_COMMAND_SaasappsaveOrUpdateOrderTendDetail = 7654,

  /// 新增照护计划
  APP_COMMAND_SaasappsaveOrderTend = 7655,

  /// 删除照护计划
  APP_COMMAND_SaasappdelOrderTend = 7656,

  /// 提交照护计划
  APP_COMMAND_SaasappsubmitOrderTend = 7657,

  /// 复制照护计划
  APP_COMMAND_SaasappcopyOrderTend = 7658,

  /// 获取补贴估算
  APP_COMMAND_SaasappgetReckonSubsidy = 7660,

  /// 获取回访记录
  APP_COMMAND_SaasappgetInsureOrderVisitList = 7700,

  /// 创建回访记录
  APP_COMMAND_SaasappaddInsureOrderVisit = 7701,

  /// 删除回访记录
  APP_COMMAND_SaasappdeleteInsureOrderVisit = 7702,

  /// 获取回访反显
  APP_COMMAND_SaasappgetInsureOrderVisitDetail = 7703,

  /// 获取回访生命体征信息
  APP_COMMAND_SaasappgetInsureOrderVisitVitaDetail = 7704,

  /// 获取质控信息
  APP_COMMAND_SaasappgetInsureOrderVisitQualityDetail = 7705,

  /// 新增修改回访生命体征信息
  APP_COMMAND_SaasappsaveOrUpdateInsureOrderVisitVita = 7706,

  /// 添加修改回访记录质控内容信息
  APP_COMMAND_SaasappsaveOrUpdateInsureOrderVisitQuality = 7707,

  /// 修改回访记录信息
  APP_COMMAND_SaasappupdateInsureOrderVisit = 7708,

  /// 获取护士回访记录
  APP_COMMAND_SaasappgetInsureOrderVisitListHs = 7709,

  /// 变更订单联系地址
  APP_COMMAND_SaasappupdateInsureOrderAddr = 7750,

  /// 获取长护险订单每日明细列表
  APP_COMMAND_SaasappgetInsureOrderTendItem = 7780,

  /// 获取长护险每日明细详情
  APP_COMMAND_SaasappgetInsureOrderTendItemDetail = 7781,

  /// 每日确认服务第一次进入设置服务地址
  APP_COMMAND_SaasappconfirmInsureOrderTendItemAddr = 7782,

  /// 确认长护险订单每日明细
  APP_COMMAND_SaasappconfirmInsureOrderTendItemDetail = 7783,

  /// 申请结束订单。推送相关
  APP_COMMAND_SaasappinsureOrderJpush = 7790,

  /// 转出订单
  APP_COMMAND_SaasapptransferInsureOrder = 7791,

  /// 获取带教记录
  APP_COMMAND_SaasappgetTeachRecord = 7792,

  /// 获取带教记录培训内容和考核内容临时值变量
  APP_COMMAND_SaasappgetTeachRecordTmpValue = 7793,

  /// 获取订单可调整状态和费用
  APP_COMMAND_SaasappgetOrderAdjustStatus = 7800,

  /// 确认订单调整信息
  APP_COMMAND_SaasappconfirmOrderAdjustStatus = 7801,

  /// 批量结算订单
  APP_COMMAND_SaasappbatchSettleOrder = 7802,

  /// 确认订单批量完成
  APP_COMMAND_SaasappconfirmOrderBatchFinish = 7803,

  /// 出入院统计
  APP_COMMAND_SaasappgetUserSituation = 7820,

  /// 出入院统计列表
  APP_COMMAND_SaasappgetUserSituationList = 7821,

  /// 修改出入院未下单状态
  APP_COMMAND_SaasappupdateUserSitution = 7822,

  /// 异常订单管理搜索订单
  APP_COMMAND_SaasappsearchAbnormalOrder = 7840,

  /// 恢复订单（把待结算的订单恢复到服务中）
  APP_COMMAND_SaasapprecoverOrder = 7841,

  /// 绑定或解绑push token 
  APP_COMMAND_SaapapppushOperation = 7845,

  ///---------saas管理后台接口
  APP_COMMAND_SaasgetPermitMenu = 9000,

  /// 获取banner列表
  APP_COMMAND_SaasgetBannerList = 9001,

  /// 保存或修改banner
  APP_COMMAND_SaassaveOrUpdateBanner = 9002,

  /// 删除一个banner
  APP_COMMAND_SaasdelBanner = 9003,

  /// 获取一个banner
  APP_COMMAND_SaasgetBannerById = 9004,

  /// 删除一个闪屏配置
  APP_COMMAND_SaasdelSplashScreen = 9005,

  /// 获取闪屏列表
  APP_COMMAND_SaasgetSplashScreenList = 9006,

  /// 保存或修改闪屏配置
  APP_COMMAND_SaassaveOrUpdateSplashScreen = 9007,

  /// 通过id获取闪屏
  APP_COMMAND_SaasgetSplashScreenById = 9008,

  /// 获取员工列表
  APP_COMMAND_SaasgetStaffList = 9009,

  /// 获取护工/护士的信息
  APP_COMMAND_SaasgetHglist = 9010,

  /// 删除护工的信息
  APP_COMMAND_SaasdelHginfo = 9011,

  /// 保存或更改护工的信息
  APP_COMMAND_SaassaveOrUpdateHginfo = 9012,

  /// 通过id获取单个护工的信息
  APP_COMMAND_SaasgetHginfo = 9013,

  ///通过id获取银行卡信息
  APP_COMMAND_SaasgetHgbankCard = 9014,

  ///通过id获取银行卡信息列表
  APP_COMMAND_SaasgetHgbankCardList = 9015,

  ///通过id删除银行卡信息
  APP_COMMAND_SaasdelHgbankCard = 9016,

  ///保存或修改银行卡信息
  APP_COMMAND_SaassaveOrUpdateHgbankCard = 9017,

  /// 保存护工的签名
  APP_COMMAND_SaasupdateHgsignPic = 9018,

  /// 获取branch有服务的列表
  APP_COMMAND_SaasgetBranchpriceList = 9020,

  /// 保存或修改branch
  APP_COMMAND_SaassaveOrUpdateBranch = 9021,

  /// 删除科室
  APP_COMMAND_SaasdeleteBranch = 9022,

  /// 获取branch
  APP_COMMAND_SaasgetBranch = 9023,

  /// 获取branch列表
  APP_COMMAND_SaasgetBranchList = 9024,

  /// 保存或修改org
  APP_COMMAND_SaassaveOrUpdateOrg = 9025,

  /// 删除机构
  APP_COMMAND_SaasdeleteOrg = 9026,

  /// 获取org
  APP_COMMAND_SaasgetOrg = 9027,

  /// 获取org列表
  APP_COMMAND_SaasgetOrgList = 9028,

  /// 保存或修改标签
  APP_COMMAND_SaassaveOrUpdateOrgTag = 9029,

  /// 删除机构标签
  APP_COMMAND_SaasdeleteOrgTag = 9030,

  /// 获取标签
  APP_COMMAND_SaasgetOrgTag = 9031,

  /// 获取org标签列表
  APP_COMMAND_SaasgetOrgTagList = 9032,

  /// 保存或修改标签
  APP_COMMAND_SaassaveOrUpdateOrgTagItem = 9033,

  /// 删除机构标签
  APP_COMMAND_SaasdeleteOrgTagItem = 9034,

  /// 获取标签
  APP_COMMAND_SaasgetOrgTagItem = 9035,

  /// 获取org标签列表
  APP_COMMAND_SaasgetOrgTagItemList = 9036,

  /// 获取机构和科室的map
  APP_COMMAND_SaasgetOrgBranchList = 9037,

  /// 保存或修改Company
  APP_COMMAND_SaassaveOrUpdateCompany = 9040,

  /// 删除公司(改变状态)
  APP_COMMAND_SaasdeleteCompany = 9041,

  /// 获取Company
  APP_COMMAND_SaasgetCompany = 9042,

  /// 获取Company列表
  APP_COMMAND_SaasgetCompanyList = 9043,

  /// 设置公司管理员
  APP_COMMAND_SaassetCompanyAdmin = 9044,

  ///公司通过申请
  APP_COMMAND_SaascompanyThroughChecking = 9046,

  ///	//获取banner最大的排序值并且获取是否存在
  APP_COMMAND_SaasgetBannerSortMax = 9047,

  /// 获取公司服务类型
  APP_COMMAND_SaasgetCompanyPriceType = 9048,

  /// 保存或修改CompanyOrg
  APP_COMMAND_SaassaveOrUpdateCompanyOrg = 9051,

  /// 删除公司机构关联
  APP_COMMAND_SaasdeleteCompanyOrg = 9052,

  /// 获取CompanyOrg
  APP_COMMAND_SaasgetCompanyOrg = 9053,

  /// 获取CompanyOrg列表
  APP_COMMAND_SaasgetCompanyOrgList = 9054,

  /// 保存或修改Room
  APP_COMMAND_SaassaveOrUpdateRoom = 9061,

  /// 删除房间
  APP_COMMAND_SaasdeleteRoom = 9062,

  /// 获取Room
  APP_COMMAND_SaasgetRoom = 9063,

  /// 获取Room列表
  APP_COMMAND_SaasgetRoomList = 9064,

  /// 查询Room列表所以
  APP_COMMAND_SaasgetRoomListInfo = 9065,

  /// 保存或修改Bed
  APP_COMMAND_SaassaveOrUpdateBed = 9071,

  /// 删除Bed
  APP_COMMAND_SaasdeleteBed = 9072,

  /// 获取Bed
  APP_COMMAND_SaasgetBed = 9073,

  /// 获取Bed列表
  APP_COMMAND_SaasgetBedList = 9074,

  /// 获取Bed列表，未被使用的
  APP_COMMAND_SaasgetBedBranchList = 9075,

  /// 获取当前用户的权限
  APP_COMMAND_SaasgetRightJson = 9080,

  /// 保存或修改定价
  APP_COMMAND_SaassaveOrUpdatePrice = 9081,

  /// 删除定价信息
  APP_COMMAND_SaasdeletePrice = 9082,

  /// 获取Price信息
  APP_COMMAND_SaasgetPrice = 9083,

  /// 获取Price列表
  APP_COMMAND_SaasgetPriceList = 9084,

  /// 修改居家预付金
  APP_COMMAND_SaassaveOrUpdateCompanyPrepay = 9085,

  /// 获取居家预付金列表
  APP_COMMAND_SaasgetCompanyPrepayList = 9086,

  /// 获取长护险居家套餐
  APP_COMMAND_SaasgetInsurePrice = 9087,

  /// 获取居家或机构套餐
  APP_COMMAND_SaasgetPriceByCreateOrder = 9088,

  /// 修改长护险信息
  APP_COMMAND_SaasupdateInsureInfo = 9089,

  /// 批量修改居家预付金
  APP_COMMAND_SaasupdateBatchCompanyPrepay = 9090,

  /// 添加或更新用户
  APP_COMMAND_SaassaveOrUpdateUser = 9091,

  /// 删除用户
  APP_COMMAND_SaasdeleteUser = 9092,

  /// 通过id获取用户
  APP_COMMAND_SaasgetUser = 9093,

  /// 获取用户列表
  APP_COMMAND_SaasgetUserList = 9094,

  /// 获取用户账户记录
  APP_COMMAND_SaasgetUserAccountRecordList = 9095,

  /// 获取用户积分记录
  APP_COMMAND_SaasgetUserIntegralRecordList = 9096,

  /// 通过手机号获取用户id，如果不存在，新增一个用户id
  APP_COMMAND_SaasgetUserByPhone = 9097,

  /// 通过住院号获取用户信息
  APP_COMMAND_SaasgetUserInfoByOrgNo = 9098,

  ///修改SAAS登录密码
  APP_COMMAND_SaaschangePwd = 9100,

  ///添加或更新APP版本记录
  APP_COMMAND_SaasaddOrUpdateAppVersion = 9120,

  ///查询APP版本列表
  APP_COMMAND_SaaslistAppVersion = 9121,

  /// 保存或修改优惠券模板
  APP_COMMAND_SaassaveOrUpdateCouponTemplate = 9130,

  /// 获取优惠券模板
  APP_COMMAND_SaasgetCouponTemplate = 9131,

  /// 获取优惠券模板列表
  APP_COMMAND_SaasgetCouponTemplateList = 9132,

  ///添加用户亲属
  APP_COMMAND_SaasaddKinsfolk = 9140,

  ///删除用户亲属
  APP_COMMAND_SaasdelKinsfolk = 9141,

  ///获取用户亲属列表
  APP_COMMAND_SaaslistKinsfolk = 9142,

  ///添加用户服务地址
  APP_COMMAND_SaasaddUserAddress = 9150,

  ///删除用户服务地址
  APP_COMMAND_SaasdelUserAddress = 9151,

  ///获取用户服务地址列表
  APP_COMMAND_SaaslistUserAddress = 9152,

  /// 获取评估点下的评估对象列表
  APP_COMMAND_SaasgetEvalKinsList = 9153,

  /// 获取我的（评估员）评估对象
  APP_COMMAND_SaasgetAssessKinsList = 9154,

  /// 生成异号用户
  APP_COMMAND_SaascreateDiffnoUser = 9155,

  /// 获取工作台信息
  APP_COMMAND_SaasgetMyWorkbench = 9160,

  /// SAAS轮询检查登录状态
  APP_COMMAND_SaascheckLoginState = 9170,

  /// 获取微信菜单列表
  APP_COMMAND_SaasgetWxmenuList = 9171,

  /// 保存或更新微信菜单
  APP_COMMAND_SaasaddOrUpdateWxmenu = 9172,

  /// 删除微信菜单
  APP_COMMAND_SaasdelWxmenu = 9173,

  /// 更新菜单到微信
  APP_COMMAND_SaasupdateMenuToWx = 9174,

  /// 更新微信自动回复语
  APP_COMMAND_SaasupdateWxautoReplay = 9175,

  /// 上传图片
  APP_COMMAND_SaasaddWxImage = 9176,

  /// 获取微信自动回复
  APP_COMMAND_SaasgetWxautoReplay = 9177,

  /// 获取提现记录
  APP_COMMAND_SaasgetWithdrawList = 9180,

  /// 获取用户支付记录
  APP_COMMAND_SaasgetUserOrderPay = 9181,

  /// 提现处理
  APP_COMMAND_Saaswithdraw = 9182,

  /// 获取长护险服务定价列表
  APP_COMMAND_SaasgetInsurePriceList = 9190,

  /// 获取长护险服务定价
  APP_COMMAND_SaasgetInsurePriceNew = 9191,

  /// 保存或修改长护险服务定价
  APP_COMMAND_SaassaveOrUpdateInsurePrice = 9192,

  /// 修改长护险服务描述
  APP_COMMAND_SaasupdateInsurePriceState = 9193,

  /// 获取订单列表
  APP_COMMAND_SaasgetOrderList = 9200,

  /// 获取订单详情
  APP_COMMAND_SaasgetOrderDetailInfo = 9201,

  /// 获取分配护工列表
  APP_COMMAND_SaasgetServeHglist = 9202,

  /// 分配护工
  APP_COMMAND_SaasallotHg = 9203,

  /// 修改订单信息
  APP_COMMAND_SaassaveOrUpdateOrder = 9204,

  /// 获取每月消费信息
  APP_COMMAND_SaasgetOrderItemList = 9205,

  /// 获取订单详情
  APP_COMMAND_SaasgetOrderInfo = 9206,

  /// 创建长护险order订单
  APP_COMMAND_SaascreateInsureOrder = 9207,

  /// 创建居家/机构订单
  APP_COMMAND_SaascreateOrder = 9208,

  /// 获取订单时间信息
  APP_COMMAND_SaasgetOrderTime = 9209,

  /// 添加居家订单评估结果
  APP_COMMAND_SaasaddOrderAssessResult = 9210,

  /// 居家订单跳过评估
  APP_COMMAND_SaasskipAssessOrder = 9211,

  /// 获取机构与科室列表
  APP_COMMAND_SaasgetOrgAndBranch = 9212,

  /// 获取房间与床位列表
  APP_COMMAND_SaasgetRoomAndBed = 9213,

  /// 获取居家订单评估结果
  APP_COMMAND_SaasgetOrderAssessResult = 9214,

  /// 获取订单中间支付详情
  APP_COMMAND_SaassettlPayDetail = 9215,

  /// 获取支付预交金详情
  APP_COMMAND_SaasprePayAmountDetail = 9216,

  ///附加服务调整明细
  APP_COMMAND_SaasappgetOrderItemInvertList = 9217,

  /// 收银台搜索订单
  APP_COMMAND_SaassearchOrder = 9218,

  /// 修改订单校正服务，修改优惠金额并关闭服务
  APP_COMMAND_SaasaddOrderPriceItemRevise = 9219,

  /// 确认订单完成
  APP_COMMAND_SaasconfirmOrderFinish = 9220,

  /// 获取附加项列表（普通附加）及反显数据
  APP_COMMAND_SaasgetOrderPriceInvert = 9221,

  /// 清空订单预交金
  APP_COMMAND_SaasclearOrderPrePayAmount = 9222,

  /// 打印
  APP_COMMAND_Saasprint = 9223,

  /// 修改订单的某个字段
  APP_COMMAND_SaasupdateOrderByField = 9224,

  /// 补录订单
  APP_COMMAND_SaasadditionalOrder = 9225,

  /// 充值预付款
  APP_COMMAND_SaasrechargePrepayFee = 9226,

  /// 计算订单费用
  APP_COMMAND_SaascalOrderFee = 9227,

  /// 关闭订单
  APP_COMMAND_SaascancelOrder = 9228,

  /// 修改订单校正服务
  APP_COMMAND_SaasaddOrderPriceItemReviseNew = 9229,

  /// 修改优惠金额并关闭服务
  APP_COMMAND_SaasupdateOrFinishOrderHgRebateFee = 9230,

  /// 订单已取消后退款
  APP_COMMAND_SaasrefundOrder = 9231,

  /// 订单服务项详情
  APP_COMMAND_SaasgetOrderItemDetail = 9232,

  /// 督导、护工开启关闭服务（新）（单纯关闭订单的改版本。对应机构订单）
  APP_COMMAND_SaassaveOrUpdateOrderNew = 9233,

  /// 修改调整订单附加服务（新）
  APP_COMMAND_SaascreateOrUpdateOrderItemPrice = 9234,

  /// 修改订单优惠方式或者优惠金额
  APP_COMMAND_SaasupdateOrderRebate = 9235,

  /// 转科室时确认新订单信息
  APP_COMMAND_SaasconfirmNewOrder = 9236,

  /// 异常订单管理搜索订单
  APP_COMMAND_SaassearchAbnormalOrder = 9237,

  /// 恢复订单（把待结算的订单恢复到服务中）
  APP_COMMAND_SaasrecoverOrder = 9238,

  /// 获取订单接诊时间
  APP_COMMAND_SaasgetOrderReceptionTime = 9239,

  /// 开启机构订单
  APP_COMMAND_SaasstartOrgOrder = 9240,

  /// 判断订单信息是否重复下单
  APP_COMMAND_SaasgetOrderRepetition = 9241,

  /// 校验是否可以结束订单
  APP_COMMAND_SaascheckFinishOrder = 9242,

  /// 确认订单调整信息
  APP_COMMAND_SaasconfirmOrderAdjustStatus = 9243,

  /// 获取订单住院号有多少待结算
  APP_COMMAND_SaasgetOrgNoorderList = 9244,

  /// 获取陪人床订单列表
  APP_COMMAND_SaasgetOrderPrclist = 9245,

  /// 获取角色列表
  APP_COMMAND_SaasgetRoleList = 9300,

  /// 获取角色
  APP_COMMAND_SaasgetRole = 9301,

  /// 新增_修改角色
  APP_COMMAND_SaassaveOrUpdateRole = 9302,

  /// 删除角色
  APP_COMMAND_SaasdelRole = 9303,

  /// 获取权限配置
  APP_COMMAND_SaasgetRightConfig = 9304,

  /// 获取权限配置列表
  APP_COMMAND_SaasgetRightConfigList = 9305,

  /// 新增_修改权限
  APP_COMMAND_SaassaveOrUpdateRightConfig = 9306,

  /// 删除权限配置
  APP_COMMAND_SaasdelRightConfig = 9307,

  /// 获取权限列表
  APP_COMMAND_SaasgetRightList = 9308,

  /// 通过角色获取人员列表
  APP_COMMAND_SaasgetHglistByRoleId = 9309,

  /// 保存角色人员
  APP_COMMAND_SaassaveHgrole = 9310,

  /// 删除护工角色
  APP_COMMAND_SaasdelHgrole = 9311,

  /// 获取不在角色的人员列表
  APP_COMMAND_SaasgetHglistNotInRoleId = 9312,

  /// 通过角色公司获取人员列表
  APP_COMMAND_SaasgetHgroleList = 9313,

  /// 获取员工角色并管辖范围
  APP_COMMAND_SaasgetUserRole = 9314,

  /// 获取权限列表(新，可根据id查询反显)
  APP_COMMAND_SaasgetRightListNew = 9315,

  /// 根据角色获取人员列表
  APP_COMMAND_SaasgetHgListByRole = 9316,

  /// 获取用户信息 用于用户详细信息页面
  APP_COMMAND_SaasgetUserInfoAll = 9350,

  /// 更新用户信息的某个字段, 用于用户详细信息页面
  APP_COMMAND_SaasupdateUserByField = 9351,

  /// 更新亲属信息的某个字段, 用于用户详细信息页面
  APP_COMMAND_SaasupdateKinsfolkByField = 9352,

  /// 为用户充值
  APP_COMMAND_SaasrechargeforUser = 9353,

  /// 根据手机号判断用户是否存在
  APP_COMMAND_SaascheckUserExist = 9354,

  /// 获取反馈信息详情
  APP_COMMAND_SaasgetFeedback = 9380,

  /// 获取反馈信息列表
  APP_COMMAND_SaasgetFeedbackList = 9381,

  /// 回复反馈
  APP_COMMAND_SaasreplyFeedback = 9382,

  /// 获取长护险申请列表
  APP_COMMAND_SaasgetInsureList = 9400,

  /// 获取长护险申请单详情
  APP_COMMAND_SaasgetInsureDetail = 9405,

  /// 审核长护险申请单
  APP_COMMAND_SaasinsureAssess = 9406,

  /// 获取长护险护士列表
  APP_COMMAND_SaasgetInsureHushiList = 9407,

  /// 指派人员
  APP_COMMAND_SaasguideStaff = 9408,

  /// 添加长护险申请
  APP_COMMAND_SaasaddInsure = 9409,

  /// ADL评估
  APP_COMMAND_SaasinsureAdlassess = 9410,

  /// 获取ADL评估结果
  APP_COMMAND_SaasgetInsureAdl = 9411,

  /// MMSE评估
  APP_COMMAND_SaassaveOrUpdateAssessMmse = 9412,

  /// 获取MMSE评估结果
  APP_COMMAND_SaasgetInsureMmse = 9413,

  /// 保存病史记录
  APP_COMMAND_SaasaddInsureMedical = 9414,

  /// 获取长护险补贴列表
  APP_COMMAND_SaasgetInsureSubsidyList = 9415,

  /// 添加长护险补贴
  APP_COMMAND_SaassaveOrUpdateInsureSubsidy = 9416,

  ///获取客服联系
  APP_COMMAND_SaasgetKfcontactRecord = 9417,

  /// 获取健康经理业绩列表
  APP_COMMAND_SaasgetInsurePerformanceList = 9418,

  /// 长护险申请单操作
  APP_COMMAND_SaasinsureAssessNew = 9419,

  /// 长护险申请单添加数据及修改
  APP_COMMAND_SaassaveOrUpdateInsure = 9420,

  /// 批量提交资料
  APP_COMMAND_SaasbatchSubmitInformation = 9421,

  /// 获取申请单详情（新）
  APP_COMMAND_SaasgetInsureDetailNew = 9422,

  /// 长护险关闭或恢复
  APP_COMMAND_SaascloseOrRecoverInsure = 9423,

  /// 新建长护险申请单
  APP_COMMAND_SaasaddInsureNew = 9430,

  /// 创建评估报告
  APP_COMMAND_SaasaddInsureAssessResult = 9500,

  /// 能力报告-生活能力
  APP_COMMAND_SaasaddInsureAssessAbilityAdl = 9501,

  /// 能力报告-精神状态
  APP_COMMAND_SaasaddInsureAssessAbilityMind = 9502,

  /// 能力报告-感知觉与沟通
  APP_COMMAND_SaasaddInsureAssessAbilityComm = 9503,

  /// 能力报告-社会参与
  APP_COMMAND_SaasaddInsureAssessAbilitySocial = 9504,

  /// 医疗照护评估
  APP_COMMAND_SaasaddInsureAssessNurse = 9505,

  /// 疾病状况评估
  APP_COMMAND_SaasaddInsureAssessIll = 9506,

  /// 社会支持评定量
  APP_COMMAND_SaasaddInsureAssessSsrs = 9507,

  /// 养老意愿评估
  APP_COMMAND_SaasaddInsureAssessTend = 9508,

  /// 提交评估报告（1，特殊情况建议2，服务建议3，签名4，更新状态）
  APP_COMMAND_SaassubmitInsureAssess = 9509,

  /// 获取评估报告
  APP_COMMAND_SaasgetInsureAssessResult = 9510,

  /// 获取历史评估记录
  APP_COMMAND_SaasgetInsureAssessResultList = 9511,

  /// 获取评估对象的评估记录
  APP_COMMAND_SaasgetKinsInsureAssessList = 9512,

  /// 完善评估对象的某个信息
  APP_COMMAND_SaasupdateInsureAssessKinsInfoByField = 9513,

  /// 完善评估对象信息
  APP_COMMAND_SaasupdateInsureAssessKinsInfo = 9514,

  /// 获取病史护理指导
  APP_COMMAND_SaasgetInsureAgainAssess = 9515,

  /// 获取老年人能力评估表-生活能力
  APP_COMMAND_SaasgetInsureAssessAbilityAdl = 9516,

  /// 获取老年人能力评估表-感知觉与沟通
  APP_COMMAND_SaasgetInsureAssessAbilityComm = 9517,

  /// 获取老年人能力评估表-精神状态
  APP_COMMAND_SaasgetInsureAssessAbilityMind = 9518,

  /// 获取老年人能力评估表-社会参与
  APP_COMMAND_SaasgetInsureAssessAbilitySocial = 9519,

  /// 获取疾病状况评估
  APP_COMMAND_SaasgetInsureAssessIll = 9520,

  /// 获取医疗照护评估
  APP_COMMAND_SaasgetInsureAssessNurse = 9521,

  /// 获取社会支持评定量表-SSRS
  APP_COMMAND_SaasgetInsureAssessSsrs = 9522,

  /// 获取养老意愿评估
  APP_COMMAND_SaasgetInsureAssessTend = 9523,

  /// 新指派人员
  APP_COMMAND_SaasguideStaffNew = 9524,

  /// 新增评估对象
  APP_COMMAND_SaasaddKins = 9550,

  /// 搜索评估对象
  APP_COMMAND_SaassearchKins = 9551,

  /// 编辑评估对象
  APP_COMMAND_SaasupdateKins = 9552,

  /// 修改评估对象的某个信息
  APP_COMMAND_SaasupdateKinsByField = 9553,

  /// 获取评估对象
  APP_COMMAND_SaasgetKins = 9554,

  /// 判断参保人状态
  APP_COMMAND_SaasgetKinsfolkIdCard = 9555,

  /// 新增评估点
  APP_COMMAND_SaasaddEvaluation = 9570,

  /// 编辑评估点
  APP_COMMAND_SaasupdateEvaluation = 9571,

  /// 获取评估点列表
  APP_COMMAND_SaasgetEvaluationList = 9572,

  /// 获取评估点
  APP_COMMAND_SaasgetEvaluation = 9573,

  /// 删除评估点
  APP_COMMAND_SaasdelEvaluation = 9574,

  ///添加资讯信息
  APP_COMMAND_SaasaddInformation = 9580,

  ///获取资讯列表
  APP_COMMAND_SaasgetInformationList = 9581,

  ///编辑资讯
  APP_COMMAND_SaasupdateInformation = 9582,

  ///删除资讯
  APP_COMMAND_SaasdelInformation = 9583,

  /// 公众号渠道二维码
  APP_COMMAND_SaasgetMpqrcode = 9590,

  /// 获取所有公众号二维码
  APP_COMMAND_SaasgetAllMpqrcode = 9591,

  ///------统计
  APP_COMMAND_Saastjhgchannel = 9600,

  /// 审核自照申请单
  APP_COMMAND_SaascheckStaffApply = 9650,

  /// 获取自照申请单列表
  APP_COMMAND_SaasgetStaffApplyList = 9651,

  /// 获取自照申请详情
  APP_COMMAND_SaasgetStaffApplyDetail = 9652,

  /// 轮询扫码支付状态
  APP_COMMAND_SaascheckSaaspayResult = 9660,

  /// 打印订单支付记录
  APP_COMMAND_SaasgetOrderPrintData = 9670,

  /// 获取居家服务类型列表
  APP_COMMAND_SaasgetIndexServiceList = 9680,

  /// 获取居家服务类型详情
  APP_COMMAND_SaasgetIndexServiceInfo = 9681,

  /// 修改居家服务类型信息
  APP_COMMAND_SaasupdateIndexService = 9682,

  /// 办理门禁卡
  APP_COMMAND_SaasaddOrderOrgExtra = 9690,

  /// 退还、挂失或解挂门禁卡
  APP_COMMAND_SaasupdateOrderOrgExtra = 9691,

  /// 门禁卡统计
  APP_COMMAND_SaastjOrgExtra = 9692,

  /// 门禁卡明细
  APP_COMMAND_SaasgetOrgExtraDetail = 9693,

  /// 批量解绑
  APP_COMMAND_SaasrelieveOrgExtra = 9694,

  /// 门禁卡管理列表
  APP_COMMAND_SaasgetExtraList = 9695,

  /// 批量插入门禁卡
  APP_COMMAND_SaasaddExtraList = 9696,

  /// 单独添加修改门禁卡
  APP_COMMAND_SaassaveOrUpdateExtra = 9697,

  /// 门禁卡详情
  APP_COMMAND_SaasgetExtraInfo = 9698,

  /// 删除门禁卡
  APP_COMMAND_SaasdeleteExtra = 9699,

  /// 获取广告位列表
  APP_COMMAND_SaasgetAdList = 9700,

  /// 获取广告位详情
  APP_COMMAND_SaasgetAd = 9701,

  /// 更新广告位信息
  APP_COMMAND_SaasupdateAd = 9702,

  /// 财务提现列表
  APP_COMMAND_SaasgetFinanceRecordList = 9720,

  /// 操作财务信息
  APP_COMMAND_SaassaveOrUpdateFinanceRecord = 9721,

  /// 统计平台资金流水
  APP_COMMAND_SaastjorderPay = 9722,

  /// 平台资金流水明细
  APP_COMMAND_SaasgetOrderPayDetail = 9723,

  /// 统计项目点资金流水
  APP_COMMAND_SaastjorderOrgPay = 9724,

  /// 项目点资金流水明细
  APP_COMMAND_SaasgetOrderOrgPayDetail = 9725,

  /// 统计陪人床数据
  APP_COMMAND_SaastjpeirenChuang = 9726,

  /// 统计陪人床数据明细
  APP_COMMAND_SaastjpeirenChuangDetail = 9727,

  /// 统计订单渠道来源
  APP_COMMAND_SaastjorderChannel = 9728,

  /// 统计订单结算
  APP_COMMAND_SaastjorderSettle = 9729,

  /// 获取报表记录
  APP_COMMAND_SaasgetFormRecordList = 9730,

  /// 生成报表报表
  APP_COMMAND_SaasgetFormRecordDownload = 9731,

  /// 生成门禁卡作废报表
  APP_COMMAND_SaasgetFormRecordExtraDownload = 9732,

  /// 生成长护险申请人名单报表
  APP_COMMAND_SaasgetFormInsureKinsfolk = 9733,

  /// 生成项目点资金流水报表
  APP_COMMAND_SaasgetFormOrderOrgPay = 9734,

  /// 生成陪人床报表
  APP_COMMAND_SaasgetFormOrderItemPrc = 9735,

  /// 生成门禁卡报表
  APP_COMMAND_SaasgetFormExtraFee = 9736,

  /// 生成护工费报表
  APP_COMMAND_SaasgetFormOrderHgFee = 9737,

  /// 获取机构消费记录
  APP_COMMAND_SaasexpenditureStatisticsJg = 9750,

  /// 获取机构消费明细
  APP_COMMAND_SaasexpenditureDetailJg = 9751,

  /// 获取机构优惠金额
  APP_COMMAND_SaasgetHgRebateDetail = 9752,

  /// 统计订单结束
  APP_COMMAND_SaastjorderFinish = 9760,

  /// 统计订单结束明细
  APP_COMMAND_SaastjorderFinishDetail = 9761,

  /// 用户支付习惯分析-医院
  APP_COMMAND_SaastjorderPayType = 9762,

  /// 用户支付习惯分析-科室
  APP_COMMAND_SaastjorderPayTypeDetail = 9763,

  /// 门禁卡费用统计报表
  APP_COMMAND_SaastjorgExtraFee = 9770,

  /// 获取门禁卡费用统计明细
  APP_COMMAND_SaasgetOrgExtraFeeDetail = 9771,

  /// 陪人床费用统计报表
  APP_COMMAND_SaastjorderItemPrc = 9772,

  /// 陪人床费用统计报表明细
  APP_COMMAND_SaastjorderItemPrcdetail = 9773,

  /// 护工费统计报表
  APP_COMMAND_SaastjorderHgFee = 9774,

  /// 企业端结算统计（督导、护工）
  APP_COMMAND_Saastjsettle = 9775,

  /// 督导服务中统计
  APP_COMMAND_SaastjorderService = 9776,

  /// 企业端结算统计获取校正（督导、护工）
  APP_COMMAND_SaasgetOrderCheck = 9777,

  /// 企业端结算统计获取护工费明细（督导、护工）
  APP_COMMAND_SaasgetOrderSettle = 9778,

  /// 督导服务中统计明细
  APP_COMMAND_SaastjorderServiceDetail = 9779,

  /// h5页面消耗统计
  APP_COMMAND_SaastjwebPageExpendTime = 9780,

  /// 统计督导企业端用户评价
  APP_COMMAND_SaastjorderPraise = 9781,

  /// 督导企业端获取用户评价
  APP_COMMAND_SaasgetOrderPraise = 9782,

  /// 统计夜陪服务
  APP_COMMAND_SaastjnightService = 9783,

  /// 获取夜陪服务明细
  APP_COMMAND_SaasgetNightService = 9784,

  /// 护工费报表明细
  APP_COMMAND_SaastjorderHgFeeDetail = 9785,

  /// 收银统计
  APP_COMMAND_Saastjcashier = 9786,

  /// 企业端结算统计(新)（督导、护工）
  APP_COMMAND_SaastjsettleNew = 9787,

  /// 企业端结算统计护工统计列表（督导）
  APP_COMMAND_SaastjsettleHgListNew = 9788,

  /// 企业端获取结算服务明细
  APP_COMMAND_SaasgetSettleNewDetail = 9789,

  /// 获取服务评价列表
  APP_COMMAND_SaasgetOrderPraiseAudit = 9790,

  /// 审核服务评价信息
  APP_COMMAND_SaasupdateOrderPraiseAudit = 9791,

  /// 回复服务评论
  APP_COMMAND_SaasreplyOrderPraiseAudit = 9792,

  /// 获取居家订单列表
  APP_COMMAND_SaasgetInsureOrderList = 9795,

  /// 接单
  APP_COMMAND_SaasacceptInsureOrder = 9796,

  /// 开启订单
  APP_COMMAND_SaasopenInsureOrder = 9797,

  /// 变更订单联系方式
  APP_COMMAND_SaasupdateInsureOrderAddr = 9798,

  /// 取消关闭订单
  APP_COMMAND_SaascancelOrderNew = 9799,

  /// 获取订单照护计划列表
  APP_COMMAND_SaasgetOrderTendList = 9800,

  /// 获取订单照护详情
  APP_COMMAND_SaasgetOrderTendDetail = 9801,

  /// 获取每日服务详情
  APP_COMMAND_SaasgetInsureOrderTendItemDetail = 9802,

  /// 获取补贴估算
  APP_COMMAND_SaasgetReckonSubsidy = 9803,

  /// 结束服务
  APP_COMMAND_SaasfinishInsureOrder = 9804,

  /// 长护险订单专用-指派人员
  APP_COMMAND_SaasguideStaffInsureOrder = 9805,

  /// 发放资质
  APP_COMMAND_SaasgrantInsureOrder = 9806,

  /// 陪人床服务
  APP_COMMAND_SaasgetWithonebedPriceList = 9810,

  /// 审核陪人床服务
  APP_COMMAND_SaasupdateWithonebedPrice = 9811,

  /// 陪人床明细
  APP_COMMAND_SaasgetWithonebedPriceDetail = 9812,

  /// 保存居家员工信息
  APP_COMMAND_SaassaveHomeHginfo = 9820,

  /// 更新居家员工信息
  APP_COMMAND_SaasupdateHomeHginfo = 9821,

  /// 获取居家护工列表
  APP_COMMAND_SaasgetHomeHglist = 9822,

  /// 管理台
  APP_COMMAND_SaasgetTurnkeyInfo = 9850,

  /// 管理台订单评价机构列表
  APP_COMMAND_SaasgetPraiseOrgList = 9851,

  /// 管理台订单评价科室列表
  APP_COMMAND_SaasgetPraiseBranchList = 9852,

  /// 管理台订单评价机构科室列表
  APP_COMMAND_SaasgetPraiseOrgBranchList = 9853,

  /// 获取管理太的机构科室数据
  APP_COMMAND_SaasgetWorkBenchOrgAndBranch = 9854,

  /// 获取病症列表
  APP_COMMAND_SaasgetIllnessList = 9890,

  /// 获取病症详情
  APP_COMMAND_SaasgetIllness = 9891,

  /// 删除病症
  APP_COMMAND_SaasdeleteIllness = 9892,

  /// 新增or修改病症维护
  APP_COMMAND_SaassaveOrUpdateIllness = 9893,

  /// 获取护照明细类型列表
  APP_COMMAND_SaasgetTendDetailTypeList = 9900,

  /// 查看照护明细类型（反显）
  APP_COMMAND_SaasgetTendDetailType = 9901,

  /// 删除照护明细类型
  APP_COMMAND_SaasdeleteTendDetailType = 9902,

  /// 新增or修改照护明细类型
  APP_COMMAND_SaassaveOrUpdateTendDetailType = 9903,

  /// 获取病症、照护明细类型列表
  APP_COMMAND_SaasgetIllnessTendDetailTypeList = 9910,

  /// 获取照护计划列表
  APP_COMMAND_SaasgetTendDetailList = 9911,

  /// 新增or修改照护计划
  APP_COMMAND_SaassaveOrUpdateTendDetail = 9912,

  /// 查看照护计划（反显）
  APP_COMMAND_SaasgetTendDetail = 9913,

  /// 删除照护计划
  APP_COMMAND_SaasdeleteTendDetail = 9914,

  /// 添加带教记录
  APP_COMMAND_SaasaddTeachRecord = 9920,

  /// 获取带教记录
  APP_COMMAND_SaasgetTeachRecord = 9921,

  /// 获取带教记录培训内容和考核内容临时值变量
  APP_COMMAND_SaasgetTeachRecordTmpValue = 9922,

  /// 添加带教记录培训内容和考核内容临时值变量
  APP_COMMAND_SaasaddTeachRecordTmpValue = 9923,

  /// 修改回访记录技能培训内容
  APP_COMMAND_SaasupdateInsureOrderVisitSkillTraning = 9925,

  /// 添加修改回访记录质控内容信息
  APP_COMMAND_SaassaveOrUpdateInsureOrderVisitQuality = 9926,

  /// 添加修改回访记录生命体征信息
  APP_COMMAND_SaassaveOrUpdateInsureOrderVisitVita = 9927,

  /// 获取回访记录质控内容信息
  APP_COMMAND_SaasgetInsureOrderVisitQuality = 9928,

  /// 获取回访记录生命体征信息
  APP_COMMAND_SaasgetInsureOrderVisitVita = 9929,

  /// 获取回访记录
  APP_COMMAND_SaasgetInsureOrderVisit = 9930,

  /// 获取自照护工列表
  APP_COMMAND_SaasgetHgapplyList = 9935,

  /// 获取自照护工信息
  APP_COMMAND_SaasgetHgapplyInfo = 9936,

  /// 获取用户黑名单列表
  APP_COMMAND_SaasgetUserShieldList = 9940,

  /// 获取用户黑名单
  APP_COMMAND_SaasgetUserShield = 9941,

  /// 添加恢复用户黑名单	
  APP_COMMAND_SaassaveOrUpdateUserShield = 9942,

  /// 新增员工信息
  APP_COMMAND_SaassaveHginfo = 9950,

  /// 修改员工信息
  APP_COMMAND_SaasupdateHginfo = 9951,

  /// 员工列表，新
  APP_COMMAND_SaasgetPersonnelList = 9952,

  /// 员工可查询的权限
  APP_COMMAND_SaasgetHgpermissionsType = 9953,

  /// 员工机构科室
  APP_COMMAND_SaasgetOrgBranchMap = 9956,

  /// 获取大屏数据
  APP_COMMAND_SaasgetBigStatistics = 9970,

  /// 获取大屏数据连接	
  APP_COMMAND_SaasgetBigURL = 9971,

  /// 批量保存院方满意度考核记录
  APP_COMMAND_SaasbatchSaveOrgSatisficing = 9975,

  /// 获取院方满意度考核
  APP_COMMAND_SaasgetOrgSatisficingById = 9976,

  /// 获取院方满意度考核记录
  APP_COMMAND_SaasgetOrgSatisficingList = 9977,

  /// 保存院方满意度考核记录
  APP_COMMAND_SaassaveOrgSatisficing = 9978,

  /// 统计院方满意度考核记录
  APP_COMMAND_SaastjOrgSatisficing = 9979,

  /// 统计陪人床（中肿） 
  APP_COMMAND_SaasgetWithonebedPriceDetailZz = 9980,

  /// 获取陪人床管理数据（中肿） 
  APP_COMMAND_SaasgetWithonebedPriceListZz = 9981,

  /// 获取陪人床订单列表（待结算）
  APP_COMMAND_SaasgetPrcchangeList = 9982,

  /// 获取陪人床调整订单明细（待结算）
  APP_COMMAND_SaasgetPrcchangeDetail = 9983,

  /// 中肿护士长调整陪人数量
  APP_COMMAND_SaaschangePrcnum = 9984,

  /// 获取微信关键字回复列表
  APP_COMMAND_SaasgetWxMsgList = 9990,

  /// 获取微信关键字回复详情
  APP_COMMAND_SaasgetWxMsgInfo = 9991,

  /// 删除微信关键字回复
  APP_COMMAND_SaasdelWxMsg = 9992,

  /// 新增或者修改微信关键字回复
  APP_COMMAND_SaassaveOrUpdateWxMsg = 9993,

  /// push结算数据到his
  APP_COMMAND_SaaspushBalanceData = 9995,

  ///  获取长护险订单回访记录pdf文件链接
  APP_COMMAND_SaasgetInsureOrderVisitPdf = 10010,

  /// 企业端陪人床订单统计
  APP_COMMAND_Saastjprcorder = 10020,

  /// 企业端陪人床订单统计详情
  APP_COMMAND_SaastjprcorderDetail = 10021,
};

GPBEnumDescriptor *APP_COMMAND_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL APP_COMMAND_IsValidValue(int32_t value);

#pragma mark - CmdRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface CmdRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
