// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Err.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum APP_ERROR_CODE

///注意：1024以下的错误码供约定俗成或者框架错误使用，业务从1025开始定义错误码
typedef GPB_ENUM(APP_ERROR_CODE) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  APP_ERROR_CODE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ///成功
  APP_ERROR_CODE_AecSuccess = 0,

  ///请求失败
  APP_ERROR_CODE_AecFault = -1,

  ///未登录或者登录失效
  APP_ERROR_CODE_AecUnlogin = 1,

  ///解密失败
  APP_ERROR_CODE_AecDecryptionFault = 2,

  ///HTTP包文Decode 失败
  APP_ERROR_CODE_AecPackageFault = 3,

  ///Command不存在
  APP_ERROR_CODE_AecCommandNotExist = 4,

  ///按照指定的command解码失败
  APP_ERROR_CODE_AecDecodeFault = 5,

  ///命令超时
  APP_ERROR_CODE_AecCommandTimeOut = 6,

  ///服务端处理异常
  APP_ERROR_CODE_AecSystemFault = 7,

  ///请求参数错误
  APP_ERROR_CODE_AecParamErr = 8,

  ///融云Token获取异常
  APP_ERROR_CODE_AecImGetTokenErr = 9,

  ///手机号为空
  APP_ERROR_CODE_AecPhoneBlank = 1100,

  ///短信发送异常
  APP_ERROR_CODE_AecSmsSendErr = 1101,

  ///短信发送频繁
  APP_ERROR_CODE_AecSmsSendFrequent = 1102,

  ///用户不存在
  APP_ERROR_CODE_AecUserNotExist = 1103,

  ///登录失败
  APP_ERROR_CODE_AecLoginVerifyFail = 1104,

  ///手机号码不正确
  APP_ERROR_CODE_AecPhoneErr = 1105,

  ///用户资料不完善
  APP_ERROR_CODE_AecProfileNotComplete = 1106,

  ///验证码错误
  APP_ERROR_CODE_AecCodeErr = 1107,

  ///验证码过期
  APP_ERROR_CODE_AecCodeExpire = 1116,

  ///第三方用户添加失败
  APP_ERROR_CODE_AecThirdUserAddFail = 1109,

  ///用户添加失败
  APP_ERROR_CODE_AecUserAddFail = 1110,

  ///第三方登录账户验证不通过
  APP_ERROR_CODE_AecThirdVerifyFail = 1111,

  ///用户被冻结
  APP_ERROR_CODE_AecUserFrozen = 1112,

  ///二维码过期
  APP_ERROR_CODE_AecQrcExpire = 1113,

  /// 确认失败
  APP_ERROR_CODE_AecConfirm = 1114,

  /// 未查询到数据
  APP_ERROR_CODE_AecPdfNothing = 1115,
};

GPBEnumDescriptor *APP_ERROR_CODE_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL APP_ERROR_CODE_IsValidValue(int32_t value);

#pragma mark - ErrRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ErrRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
